import MyModal from '@/components/MyModal/MyModal';
import React from 'react';
import { useSaveMedicalSheetMutation } from '@/services/setupService';
import MyInput from '@/components/MyInput';
import { Form } from 'rsuite';
import { useDispatch } from 'react-redux';
import { notify } from '@/utils/uiReducerActions';
import { faSheetPlastic } from '@fortawesome/free-solid-svg-icons';
import './styles.less';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

const ChooseDepartment = ({
  open,
  setOpen,
  width,
  showScreen,
  setShowScreen,
  department
}) => {
  const dispatch = useDispatch();
  // Save MedicalSheet
  const [saveMedicalSheet] = useSaveMedicalSheetMutation();

  // Handle save MedicalSheet
  const handleSave = () => {
    try {
      saveMedicalSheet({ ...showScreen, departmentKey: department.key }).unwrap();
      dispatch(notify({ msg: 'Saved successfully', sev: 'success' }));
      setOpen(false);
    } catch (error) {
      dispatch(notify({ msg: 'Saved Faild', sev: 'error' }));
    }
  };
  // Modal content
  const conjureFormContent = (stepNumber = 0) => {
    switch (stepNumber) {
      case 0:
        return (

          <Form layout='inline' fluid >
            <div className="container-of-medical-sheets">
              <div className="container-of-specific-sheets">
                <h6>Default Sheets</h6>
                <MyInput
                  fieldType="check"
                  fieldName={''}
                  fieldLabel={'Select All'}
                  showLabel={false}
                  record={''}
                  setRecord={() => ''}
                />

                <div className="sheets">
                  <MyInput
                    fieldType="check"
                    fieldName={'patientDashboard'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'clinicalVisit'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'observation'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'diagnosticsOrder'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'prescription'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'drugOrder'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'consultation'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'procedures'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'patientHistory'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'allergies'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'medicalWarnings'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'medicationsRecord'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'vaccineReccord'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'diagnosticsResult'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'operationRequests'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen} />
                  <MyInput
                    fieldType="check"
                    fieldName={'doctorRound'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'dayCase'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'bedsideProceduresRequest'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'referralRequest'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'bloodOrder'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'ivFluidOrder'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'intakeOutputBalance'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'riskAssessments'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'multidisciplinaryTeamNotes'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'nutritionStateAssessment'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'physicianOrderSummary'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'carePlanAndGoals'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'dischargePlanning'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'johnsHopkinsFallRiskAssessmentTool'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'morseFallScale'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'hendrichFallRisk'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'stratifyScale'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'bradenScaleForPressureUlcer'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />


                  <MyInput
                    fieldType="check"
                    fieldName={'glasgowComaScale'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />

                  <MyInput
                    fieldType="check"
                    fieldName={'vteRiskAssessment'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'progressNotes'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'medicationAdministrationRecord'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'ivFluidAdministration'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'dietaryRequest'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'dietaryRequest'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'continuousObservations'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                    <MyInput
                    fieldType="check"
                    fieldName={'dialysisRequest'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                      <MyInput
                    fieldType="check"
                    fieldName={'slidingScale'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                       <MyInput
                    fieldType="check"
                    fieldName={'pointOfCareCests'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                        <MyInput
                    fieldType="check"
                    fieldName={'hospitalCourse'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                       <MyInput
                    fieldType="check"
                    fieldName={'childGrowth'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                   <MyInput
                    fieldType="check"
                    fieldName={'flaccNeonatesPainAssessment'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                      <MyInput
                    fieldType="check"
                    fieldName={'universalPainAssessment'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                        <MyInput
                    fieldType="check"
                    fieldName={'patientRestraint'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                        <MyInput
                    fieldType="check"
                    fieldName={'infectionControl'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'sofa'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                   <MyInput
                    fieldType="check"
                    fieldName={'medicalCalculators'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'cpoeResultsManager'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                </div>
              </div>
              <div className="container-of-specific-sheets">
                <h6>Specialty Sheets</h6>
                <MyInput
                  fieldType="check"
                  fieldName={''}
                  fieldLabel={'Select All'}
                  showLabel={false}
                  record={''}
                  setRecord={() => ''}
                />
                <div className="sheets">
                  <MyInput
                    fieldType="check"
                    fieldName={'psychologicalExam'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'audiometryPuretone'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'optometricExam'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'dentalCare'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'cardiology'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'vaccination'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'pregnancyFollowUp'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'pediatric'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'gynecology'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'speechTherapy'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'rehabilitationPlan'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'occupationalTherapy'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                  <MyInput
                    fieldType="check"
                    fieldName={'physiotherapyPlan'}
                    showLabel={false}
                    record={showScreen}
                    setRecord={setShowScreen}
                  />
                </div>
              </div>
            </div>
          </Form>
        );
    }
  };
  return (
    <MyModal
      open={open}
      setOpen={setOpen}
      title='Medical Sheets'
      position="right"
      content={conjureFormContent}
      actionButtonLabel='Save'
      actionButtonFunction={handleSave}
      size={width > 600 ? '36vw' : '25vw'}
      steps={[{ title: 'Medical Sheets', icon: <FontAwesomeIcon icon={faSheetPlastic} /> }]}
    />
  );
};
export default ChooseDepartment;
