
import React, { useEffect, useMemo, useState } from 'react';
import { Col, Divider, Form, Row, Tabs } from 'rsuite';
import MyModal from '@/components/MyModal/MyModal';
import Translate from '@/components/Translate';
import './PreviewCalendar.less';
import MyInput from '@/components/MyInput';
import WarningMessage from './WarningMessage';



type Props = {
    open: boolean;
    setOpen: any;
    template: any;

};



const AddExceptionModal: React.FC<Props> = ({ open, setOpen, template }) => {

    const [record, setRecord] = useState(
        {
            exceptionSchedule: "",
            date: "",
            hour: "",
            fromDate: "",
            toDate: "",
            fromHour: "",
            toHour: "",
        }
    )

    const exceptionScheduleChoices =
        [
            { label: "Single Date", value: "singleDate" },
            { label: "Date Range", value: "dateRange" },
            { label: "Recurring", value: "recurring" }
        ]

    const exceptionReasons = [
        { label: "Department Training", value: "departmentTraining" },
        { label: "Vacation", value: "vacation" },
        { label: "Equipment Maintenance", value: "equipmentMaintenance" },
        { label: "Other", value: "other" }
    ]



    return (
        <MyModal
            open={open}
            setOpen={setOpen}
            size="sm"
            title="Add Exception"
            content={
                <>
                    <Form fluid>
                         <WarningMessage
                        message='This exception will override availability generated by templates.'
                    />
                    <br />
                        <MyInput
                            width="100%"
                            fieldName="exceptionSchedule"
                            fieldType="select"
                            selectData={exceptionScheduleChoices}
                            selectDataLabel="label"
                            selectDataValue="value"
                            fieldLabel="Exception Schedule"
                            record={record}
                            setRecord={setRecord}
                            searchable={false}
                        />
                        {record['exceptionSchedule'] === 'singleDate' ? (
                            <Row>
                                <Col md={16}>
                                    <MyInput
                                        width="100%"
                                        fieldName="date"
                                        fieldType="date"
                                        record={record}
                                        setRecord={setRecord}
                                    />
                                </Col>
                                <Col md={8}>
                                    <MyInput
                                        width="100%"
                                        fieldName="hour"
                                        fieldType="time"
                                        record={record}
                                        setRecord={setRecord}
                                    />
                                </Col>
                            </Row>
                        ) : record['exceptionSchedule'] === 'dateRange' ? (
                            <>
                                <Row>
                                    <Col md={16}>
                                        <MyInput
                                            width="100%"
                                            fieldName="fromDate"
                                            fieldType="date"
                                            record={record}
                                            setRecord={setRecord}
                                        />
                                    </Col>
                                    <Col md={8}>
                                        <MyInput
                                            width="100%"
                                            fieldName="fromHour"
                                            fieldType="time"
                                            record={record}
                                            setRecord={setRecord}
                                        />
                                    </Col>
                                </Row>
                                <Row>
                                    <Col md={16}>
                                        <MyInput
                                            width="100%"
                                            fieldName="toDate"
                                            fieldType="date"
                                            record={record}
                                            setRecord={setRecord}
                                        />
                                    </Col>
                                    <Col md={8}>
                                        <MyInput
                                            width="100%"
                                            fieldName="toHour"
                                            fieldType="time"
                                            record={record}
                                            setRecord={setRecord}
                                        />
                                    </Col>
                                </Row>
                            </>
                        ) : (
                            <></>
                        )
                        }
                        <MyInput
                            width="100%"
                            fieldName=""
                            fieldType="select"
                            selectData={exceptionReasons}
                            selectDataLabel="label"
                            selectDataValue="value"
                            fieldLabel="Reason"
                            record={record}
                            setRecord={setRecord}
                        />
                    </Form>
                </>
            }
        />
    );
};

export default AddExceptionModal;
