export interface ApAccessRole { 
	key:string;
	name:string;
	description:string;
	accessLevel:number;
	passwordErrorRetires:number;
	passwordExpires:boolean;
	passwordExpiresAfterDays:number;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApAccessRoleAuthorization { 
	key:string;
	accessRoleKey:string;
	authorizationType:string;
	authorizationObjectKey:string;
	authorizationLevel:number;
	accessLevel:number;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApAccessRoleScreen { 
	key:string;
	accessRoleKey:string;
	screenKey:string;
	canRead:boolean;
	canWrite:boolean;
	canDelete:boolean;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApAccessToken { 
	key:string;
	userKey:string;
	canExpire:boolean;
	expiresAt:number;
	accessToken:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApActiveIngredient { 
	key:string;
	code:string;
	name:string;
	hasSalt:boolean;
	saltLkey:string;
	medicalCategoryLkey:string;
	isControlled:boolean;
	controlledLkey:string;
	hasSynonyms:boolean;
	chemicalFormula:string;
	drugTypeLkey:string;
	drugClassLkey:string;
	hasBlackBoxWarning:boolean;
	blackBoxWarning:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	mechanismOfAction:string;
	toxicityMaximumDose:string;
	toxicityMaximumDosePerUnitLkey:string;
	toxicityDetails:string;
	pregnancyCategoryLkey:string;
	pregnancyNotes:string;
	lactationRiskLkey:string;
	lactationRiskNotes:string;
	doseAdjustmentRenal:boolean;
	doseAdjustmentHepatic:boolean;
	pharmaAbsorption:string;
	pharmaRouteOfElimination:string;
	pharmaVolumeOfDistribution:string;
	pharmaHalfLife:string;
	pharmaProteinBinding:string;
	pharmaClearance:string;
	pharmaMetabolism:string;
	doseAdjPugA:string;
	doseAdjPugB:string;
	doseAdjPugC:string;
	doseAdjRenalOne:string;
	doseAdjRenalTwo:string;
	doseAdjRenalThree:string;
	doseAdjRenalFour:string;
} 

export interface ApActiveIngredientAdverseEffect { 
	key:string;
	activeIngredientKey:string;
	adverseEffectLkey:string;
	isOther:boolean;
	otherDescription:string;
	typeLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApActiveIngredientContraindication { 
	key:string;
	activeIngredientKey:string;
	contraindication:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApActiveIngredientDrugInteraction { 
	key:string;
	activeIngredientKey:string;
	interactedActiveIngredientKey:string;
	severityLkey:string;
	description:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApActiveIngredientFoodInteraction { 
	key:string;
	activeIngredientKey:string;
	foodDescription:string;
	severityLkey:string;
	description:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApActiveIngredientIndication { 
	key:string;
	activeIngredientKey:string;
	indication:string;
	isOffLabel:boolean;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApActiveIngredientRecommendedDosage { 
	key:string;
	activeIngredientKey:string;
	indicationLkey:string;
	variableLkey:string;
	dosage:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApActiveIngredientSpecialPopulation { 
	key:string;
	activeIngredientKey:string;
	additionalPopulationLkey:string;
	considerations:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApActiveIngredientSynonym { 
	key:string;
	activeIngredientKey:string;
	synonym:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApAddresses { 
	key:string;
	entityId:string;
	entityTypeLkey:string;
	addressTypeLkey:string;
	streetAddressLine1:string;
	streetAddressLine2:string;
	countryLkey:string;
	stateProvinceRegionLkey:string;
	cityLkey:string;
	postalCode:string;
	additionalInfo:string;
	latitude:string;
	longitude:string;
	isActive:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApAgeGroup { 
	key:string;
	ageGroupLkey:string;
	fromAge:number;
	toAge:number;
	fromAgeUnitLkey:string;
	toAgeUnitLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApAllergens { 
	key:string;
	allergenCode:string;
	allergenName:string;
	allergenTypeLkey:string;
	description:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApAppointment { 
	key:string;
	patientKey:string;
	facilityKey:string;
	resourceTypeLkey:string;
	visitTypeLkey:string;
	durationLkey:string;
	appointmentStart:string;
	instructionsLkey:string;
	notes:string;
	priorityLkey:string;
	isReminder:string;
	reminderLkey:string;
	consentForm:string;
	referingPhysicianLkey:string;
	externalPhysician:string;
	procedureLevelLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	resourceKey:string;
	resourceLkey:string;
} 

export interface ApAttachment { 
	key:string;
	attachmentType:string;
	referenceObjectKey:string;
	extraDetails:string;
	fileName:string;
	contentType:string;
	fileContent:uint8array;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	details:string;
	accessTypeLkey:string;
} 

export interface ApCatalogDiagnosticTest { 
	key:string;
	testKey:string;
	catalogKey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApCdt { 
	key:string;
	typeLkey:string;
	cdtCode:string;
	description:string;
	classLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApCdtDentalAction { 
	key:string;
	dentalActionKey:string;
	cdtKey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApClinicalDocumentation { 
	key:string;
	patientKey:string;
	encounterKey:string;
	docTypeLkey:string;
	docCategoryLkey:string;
	docContent:string;
	userKey:string;
	userRoleLkey:string;
	facilityKey:string;
	docStatusLkey:string;
	docFormTypeKey:string;
	docFormKey:string;
	createdDatetime:Date;
	approvedDatetime:Date;
	approvedByUserKey:string;
	approvedByUserRoleLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApCustomeInstructions { 
	key:string;
	prescriptionMedicationsKey:string;
	dose:number;
	frequencyLkey:string;
	unitLkey:string;
	roaLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApDentalAction { 
	key:string;
	description:string;
	type:string;
	imageName:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	favorite:boolean;
} 

export interface ApDentalChart { 
	key:string;
	encounterKey:string;
	patientKey:string;
	chartDate:Date;
	type:string;
	chartSequence:number;
	status:string;
	treatmentPlan:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApDentalChartProgressNote { 
	key:string;
	chartKey:string;
	note:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApDentalChartTooth { 
	key:string;
	chartKey:string;
	toothNumber:string;
	missing:boolean;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	toothNumberNumeric:number;
} 

export interface ApDentalPlannedTreatment { 
	key:string;
	patientKey:string;
	encounterKey:string;
	type:string;
	visitNumber:number;
	cdtKey:string;
	toothKey:string;
	note:string;
	surfaceLkey:string;
	billingTypeLkey:string;
	fees:number;
	insurance:number;
	discount:number;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	statusLkey:string;
	source:string;
	sourceKey:string;
} 

export interface ApDepartment { 
	key:string;
	facilityKey:string;
	name:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	departmentTypeLkey:string;
	appointable:boolean;
	hasTriage:boolean;
	departmentCode:string;
} 

export interface ApDiagnosticTest { 
	key:string;
	testTypeLkey:string;
	testName:string;
	internalCode:string;
	internationalCodeOne:string;
	internationalCodeTwo:string;
	internationalCodeThree:string;
	ageSpecific:boolean;
	genderSpecific:boolean;
	genderLkey:string;
	specialPopulation:boolean;
	price:number;
	currencyLkey:string;
	specialNotes:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApDiagnosticTestAgeType { 
	key:string;
	testKey:string;
	ageFrom:number;
	ageTo:number;
	ageTypeLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApDiagnosticTestCatalogHeader { 
	key:string;
	description:string;
	typeLkey:string;
	departmentKey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	testKey:string;
	catalogKey:string;
} 

export interface ApDiagnosticTestEyeExam { 
	key:string;
	testKey:string;
	eyeExamCategoryLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApDiagnosticTestGenetics { 
	key:string;
	testKey:string;
	internationalCodingTypeLkey:string;
	childCodeLkey:string;
	pathologyCategoryLkey:string;
	specimenTypeLkey:string;
	methodologyLkey:string;
	turnaroundTime:string;
	timeUnitLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApDiagnosticTestPathology { 
	key:string;
	testKey:string;
	internationalCodingTypeLkey:string;
	childCodeLkey:string;
	pathologyCategoryLkey:string;
	specimenTypeLkey:string;
	analysisProcedureLkey:string;
	turnaroundTime:string;
	timeUnitLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApDiagnosticTestRadiology { 
	key:string;
	testKey:string;
	internationalCodingTypeLkey:string;
	childCodeLkey:string;
	radCategoryLkey:string;
	imageDuration:string;
	timeUnitLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	labCatalogLkey:string;
	propertyLkey:string;
	systemLkey:string;
	scaleLkey:string;
	reagentsLkey:string;
	methodLkey:string;
	timingLkey:string;
	resultType:string;
	resultUnitLkey:string;
} 

export interface ApDiagnosticTestSpecialPopulation { 
	key:string;
	testKey:string;
	specialPopulationLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApDvmRule { 
	key:string;
	screenMetadataKey:string;
	ruleDescription:string;
	fieldKey:string;
	fieldName:string;
	fieldDataType:string;
	isFieldLov:boolean;
	isFieldRef:boolean;
	ruleType:string;
	ruleValue:string;
	ruleValueTwo:string;
	isDependant:boolean;
	dependantRuleCheck:string;
	dependantRuleKey:string;
	validationType:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApEncounter { 
	key:string;
	patientKey:string;
	patientFullName:string;
	patientAge:string;
	encounterStatusLkey:string;
	encounterClassLkey:string;
	encounterPriorityLkey:string;
	encounterTypeLkey:string;
	serviceTypeLkey:string;
	patientStatusLkey:string;
	episodeCareKey:string;
	basedOnLkey:string;
	basedOnKey:string;
	partOfEncounterKey:string;
	attendingPhysicianKey:string;
	responsiblePhysicianKey:string;
	facilityKey:string;
	appointmentKey:string;
	virtualService:boolean;
	plannedStartDate:Date;
	plannedEndDate:Date;
	actualStartDate:Date;
	actualEndDate:Date;
	actualLengthHrs:number;
	reasonLkey:string;
	primaryDiagnoseKey:string;
	dietPreferenceLkey:string;
	dietPreferenceText:string;
	valuableItemsText:string;
	specialArrangementLkey:string;
	specialArrangementText:string;
	specialCourtesyLkey:string;
	admissionOrigin:string;
	admissionSource:string;
	readmission:boolean;
	dischargeDestination:string;
	dischargeDisposition:string;
	locationTypeLkey:string;
	locationKey:string;
	followUpEncounterKey:string;
	queueNumber:number;
	billingAccountKey:string;
	paymentTypeLkey:string;
	payerTypeLkey:string;
	payerKey:string;
	insurancePlan:string;
	payerMemberId:string;
	referralNumber:string;
	accessLevel:number;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	departmentKey:string;
	dischargeTypeLkey:string;
	actualLengthMinutes:number;
	chiefComplaint:string;
	hpiSummery:string;
	hpiKey:string;
	pastMedicalHistorySummery:string;
	pastMedicalHistoryKey:string;
	rosSummery:string;
	rosKey:string;
	assessmentSummery:string;
	assessmentKey:string;
	physicalExamSummery:string;
	physicalExamSummeryKey:string;
	progressNote:string;
	dischargeNote:string;
	dischargeSummery:string;
	visitId:string;
	encounterNotes:string;
	sourceName:string;
	physicalExamNote:string;
} 

export interface ApEncounterAppliedService { 
	key:string;
	encounterKey:string;
	serviceKey:string;
	categoryLkey:string;
	source:string;
	sourceKey:string;
	extraDetails:string;
	price:number;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApFacility { 
	key:string;
	facilityId:string;
	facilityName:string;
	facilityNameOtherLang:string;
	tenantId:string;
	facilityRegistrationDate:Date;
	facilityEmailAddress:string;
	facilityBriefDesc:string;
	facilityAddressOtherLang:string;
	facilityLogoFile:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	facilityPhone1:string;
	facilityPhone2:string;
	facilityFax:string;
	facilityAddressId:string;
	facilityTypeLkey:string;
	facilityType:string;
	facilityAddress:string;
} 

export interface ApGenericMedication { 
	key:string;
	genericName:string;
	manufacturerLkey:string;
	usageInstructions:string;
	roaLkey:string;
	dosageFormLkey:string;
	expiresAfterOpening:boolean;
	expiresAfterOpeningValue:string;
	singlePatientUse:boolean;
	price:number;
	currencyLkey:string;
	priceListKey:string;
	cost:number;
	storageRequirements:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApGlobalSettings { 
	key:string;
	facilityKey:string;
	settingKey:string;
	settingValue:string;
	settingCategory:string;
	requireRestart:boolean;
	requirePasscode:boolean;
	fixedValue:boolean;
	forAdminUse:boolean;
	hiddenSetting:boolean;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApIcdCode { 
	key:string;
	icdVersion:string;
	icdCode:string;
	description:string;
	chapter:string;
	block:string;
	category:string;
	subcategory:string;
	fulldescription:string;
	includes:string;
	excludes1:string;
	excludes2:string;
	useadditionalcode:string;
	codefirst:string;
	codingguidelines:string;
	clinicaldescription:string;
	severity:string;
	synonyms:string;
	abbreviations:string;
	notes:string;
	requireSide:string;
	requireDetails:string;
	linkedWithAge:string;
	linkedWithGender:string;
	linkedWithDisease:string;
	moreSpecification:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApLanguages { 
	key:string;
	languageCode:string;
	languageName:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApLicense { 
	key:string;
	tenantId:string;
	licenseId:string;
	licenseKey:string;
	licenseType:string;
	startDate:Date;
	endDate:Date;
	activestatus:boolean;
	uuidHwKeys:string;
	facilityAddress:string;
	facilityLogoFile:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApLicenseDetails { 
	key:string;
	tenantId:string;
	licenseId:string;
	facilityCount:number;
	bedCount:number;
	userCount:number;
	modules:string;
	facilityUsageCount:number;
	bedUsageCount:number;
	userUsageCount:number;
	lastUsageDate:Date;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApLov { 
	key:string;
	lovCode:string;
	lovName:string;
	lovDescription:string;
	loveCustomCode:string;
	parentLov:string;
	autoSelectDefault:boolean;
	defaultValueId:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApLovValues { 
	key:string;
	lovKey:string;
	lovCode:string;
	valueCode:string;
	lovDisplayVale:string;
	loveCustomCode:string;
	valueDescription:string;
	valueColor:number;
	valueIcon:string;
	valueOrder:number;
	isdefault:boolean;
	seededData:boolean;
	forInternalUser:boolean;
	specificForScreenId:string;
	parentValueId:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApMessages { 
	key:string;
	messageId:string;
	messageCode:string;
	messageType:string;
	messageHeader:string;
	messageText:string;
	languageCode:string;
	isoriginalMessage:boolean;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApMetadata { 
	key:string;
	objectName:string;
	dbObjectName:string;
	description:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApMetadataField { 
	key:string;
	fieldName:string;
	dbFieldName:string;
	metadataKey:string;
	dbObjectName:string;
	dataType:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApModule { 
	key:string;
	name:string;
	description:string;
	iconImagePath:string;
	viewOrder:number;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApPatient { 
	key:string;
	patientMrn:string;
	namePrefix:string;
	nameSuffix:string;
	patientAlias:string;
	firstName:string;
	secondName:string;
	thirdName:string;
	lastName:string;
	fullName:string;
	secondNameOtherLang:string;
	firstNameOtherLang:string;
	thirdNameOtherLang:string;
	lastNameOtherLang:string;
	fullNameOtherLang:string;
	documentCountryLkey:string;
	documentTypeLkey:string;
	documentNo:string;
	noDocument:boolean;
	specialCourtesyLkey:string;
	unknown:string;
	genderLkey:string;
	phoneNumber:string;
	mobileNumber:string;
	email:string;
	maritalStatusLkey:string;
	nationalityLkey:string;
	primaryLanguageLkey:string;
	religionLkey:string;
	ethnicityLkey:string;
	occupationLkey:string;
	emergencyContactName:string;
	emergencyContactRelationLkey:string;
	emergencyContactPhone:string;
	streetAddressLine1:string;
	streetAddressLine2:string;
	countryLkey:string;
	stateProvinceRegionLkey:string;
	cityLkey:string;
	postalCode:string;
	additionalInfo:string;
	latitude:number;
	longitude:string;
	isActive:string;
	deathDatetime:Date;
	dob:Date;
	multipleBirth:boolean;
	birthOrder:number;
	numSiblings:number;
	accessLevel:number;
	facilityKey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	patientClassLkey:string;
	privatePatient:boolean;
	verificationOtp:string;
	securityAccessLevelLkey:string;
	socialSecurityNumber:string;
	noticeOfPrivacyPractice:boolean;
	noticeOfPrivacyPracticeDate:Date;
	privacyAuthorization:boolean;
	privacyAuthorizationDate:Date;
	consent:boolean;
	consentDate:Date;
	verified:boolean;
	responsiblePartyLkey:string;
	educationalLevelLkey:string;
	previousId:string;
	archivingNumber:string;
	receiveSms:boolean;
	receiveEmail:boolean;
	homePhone:string;
	workPhone:string;
	preferredContactLkey:string;
	unknownPatient:boolean;
	incompletePatient:boolean;
	extraDetails:string;
	secondaryMobileNumber:string;
	districtLkey:string;
} 

export interface ApPatientAddresses { 
	key:string;
	patientKey:string;
	addressTypeLkey:string;
	streetAddressLine1:string;
	streetAddressLine2:string;
	countryLkey:string;
	stateProvinceRegionLkey:string;
	cityLkey:string;
	postalCode:string;
	additionalInfo:string;
	latitude:number;
	longitude:string;
	isActive:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApPatientAdministrativeWarnings { 
	key:string;
	patientKey:string;
	warningTypeLkey:string;
	description:string;
	resolutionStatusLkey:string;
	dateResolved:Date;
	resolvedBy:string;
	resolutionUndoDate:Date;
	resolvedUndoBy:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApPatientAlerts { 
	key:string;
	patientKey:string;
	alertTypeLkey:string;
	alertSourceLkey:string;
	alertDescription:string;
	alertSeverityLkey:string;
	isResolved:boolean;
	alertDate:Date;
	dateResolved:Date;
	notes:string;
	sourceOfInfoLkey:string;
	sourceKey:string;
	lifeThreating:boolean;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApPatientAllergies { 
	key:string;
	patientKey:string;
	allergyKey:string;
	allergenTypeLkey:string;
	severityLkey:string;
	reaction:string;
	dateDiagnosed:Date;
	resolutionStatusLkey:string;
	dateResolved:Date;
	treatmentPlan:string;
	notes:string;
	sourceOfInfoLkey:string;
	lifeThreating:boolean;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	addedByVisitKey:string;
} 

export interface ApPatientDiagnose { 
	key:string;
	patientKey:string;
	visitKey:string;
	diagnoseCode:string;
	description:string;
	diagnoseCodingLkey:string;
	dateDiagnosed:Date;
	onsetDate:Date;
	diagnoseStatusLkey:string;
	diagnoseTypeLkey:string;
	diagnoseSiteLkey:string;
	providerTypeLkey:string;
	providerLkey:string;
	providerUserName:string;
	providerRoleLkey:string;
	notes:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	isMajor:boolean;
	isSuspected:boolean;
} 

export interface ApPatientEncounterOrder { 
	key:string;
	patientKey:string;
	visitKey:string;
	testKey:string;
	statusLkey:string;
	receivedLabLkey:string;
	reasonLkey:string;
	priorityLkey:string;
	notes:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApPatientIds { 
	key:string;
	patientKey:string;
	identifierTypeLovKey:string;
	identifierCode:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApPatientInsurance { 
	key:string;
	patientKey:string;
	insuranceProviderLkey:string;
	primaryInsurance:boolean;
	insurancePolicyNumber:string;
	groupNumber:string;
	insurancePlanTypeLkey:string;
	authorizationNumbers:string;
	expirationDate:Date;
	coPayment:boolean;
	coPaymentValue:number;
	coInsurance:boolean;
	coInsuranceValue:number;
	deductibles:boolean;
	deductiblesValue:number;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	policyHolder:string;
} 

export interface ApPatientInsuranceCoverage { 
	key:string;
	patientInsuranceKey:string;
	typeLkey:string;
	coverageTypeLkey:string;
	coveredAmount:number;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApPatientObservation { 
	key:string;
	patientKey:string;
	visitKey:string;
	observationDate:Date;
	observationTypeLkey:string;
	value:string;
	value2:string;
	unitofMeasureLkey:string;
	referencerangeLkey:string;
	statusLkey:string;
	methodLkey:string;
	positionLkey:string;
	siteLkey:string;
	equipmentUsedLkey:string;
	comments:string;
	sourceRecordKey:string;
	providerKey:string;
	providerName:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApPatientObservationSummary { 
	key:string;
	patientKey:string;
	visitKey:string;
	lastDate:Date;
	latesttemperature:number;
	latestbpSystolic:number;
	latestbpDiastolic:number;
	latestheartrate:number;
	latestrespiratoryrate:number;
	latestoxygensaturation:number;
	latestglucoselevel:number;
	latestpainlevelLkey:string;
	latestweight:number;
	latestheight:number;
	latestheadcircumference:number;
	latestlength:number;
	latestbmi:number;
	age:number;
	prevRecordKey:string;
	plastDate:Date;
	platesttemperature:number;
	platestbpSystolic:number;
	platestbpDiastolic:number;
	platestheartrate:number;
	platestrespiratoryrate:number;
	platestoxygensaturation:number;
	platestglucoselevel:number;
	platestpainlevelLkey:string;
	platestweight:number;
	platestheight:number;
	platestheadcircumference:number;
	platestlength:number;
	platestbmi:number;
	page:number;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	latestnotes:string;
	platestnotes:string;
	latestpaindescription:string;
	platestpaindescription:string;
	latestpainlevel:number;
	platestpainlevel:number;
} 

export interface ApPatientPlan { 
	key:string;
	patientKey:string;
	visitKey:string;
	physicianRecommendations:string;
	patientEducations:string;
	lifestyleModifications:string;
	generalInstructions:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApPatientProblem { 
	key:string;
	patientKey:string;
	problemCode:string;
	description:string;
	problemCodingLkey:string;
	dateDiagnosed:Date;
	problemStatusLkey:string;
	severityLkey:string;
	onSetDate:Date;
	providerTypeLkey:string;
	providerLkey:string;
	providerUserName:string;
	providerRoleLkey:string;
	resolvedDate:Date;
	dateAdded:Date;
	notes:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApPatientRelation { 
	key:string;
	patientKey:string;
	relativePatientKey:string;
	relationTypeLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	categoryTypeLkey:string;
} 

export interface ApPatientSecondaryDocuments { 
	key:string;
	documentCountryLkey:string;
	documentTypeLkey:string;
	documentNo:string;
	patientKey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApPhysicalExamArea { 
	key:string;
	patientKey:string;
	encounterKey:string;
	physicalExamAreaLkey:string;
	physicalExamAreaDetailLkey:string;
	notes:string;
	sourceOfAnswerLkey:string;
	pass:boolean;
	passReasonLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApPractitioner { 
	key:string;
	primaryFacilityKey:string;
	practitionerFullName:string;
	genderLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	departmentKey:string;
	practitionerFirstName:string;
	practitionerLastName:string;
	practitionerEmail:string;
	practitionerPhoneNumber:string;
	jobRole:string;
	specialtyLkey:string;
	subSpecialtyLkey:string;
	defaultMedicalLicense:string;
	secondaryMedicalLicense:string;
	educationalLevelLkey:string;
	professionalMembershipAndCertification:string;
	appointable:boolean;
	linkedUser:string;
	defaultLicenseValidUntil:Date;
	secondaryLicenseValidUntil:Date;
	dob:Date;
} 

export interface ApPrescription { 
	key:string;
	patientKey:string;
	visitKey:string;
	statusLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApPrescriptionInstruction { 
	key:string;
	categoryLkey:string;
	dose:number;
	unitLkey:string;
	routLkey:string;
	frequencyLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApPrescriptionMedications { 
	key:string;
	patientKey:string;
	visitKey:string;
	prescriptionKey:string;
	genericMedicationsKey:string;
	numberOfRefills:number;
	refillInterval:string;
	instructionsTypeLkey:string;
	instructions:string;
	notes:string;
	parametersToMonitor:string;
	validUtil:Date;
	maximumDose:number;
	genericSubstitute:boolean;
	chronicMedication:boolean;
	administrationInstructions:string;
	duration:number;
	durationTypeLkey:string;
	statusLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApResources { 
	key:string;
	facilityKey:string;
	resourceTypeLkey:string;
	resourceKey:string;
	isAllowParallel:boolean;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApResourcesAvailabilityTime { 
	key:string;
	resourceKey:string;
	facilityKey:string;
	departmentKey:string;
	dayLkey:string;
	startTime:number;
	endTime:number;
	isHasBreak:boolean;
	breakFrom:number;
	breakTo:number;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApReviewOfSystem { 
	key:string;
	patientKey:string;
	encounterKey:string;
	systemLkey:string;
	systemDetailLkey:string;
	notes:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApScreen { 
	key:string;
	name:string;
	description:string;
	moduleKey:string;
	iconImagePath:string;
	viewOrder:number;
	navPath:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApScreenMetadata { 
	key:string;
	screenKey:string;
	metadataKey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApService { 
	key:string;
	typeLkey:string;
	name:string;
	abbreviation:string;
	code:string;
	categoryLkey:string;
	price:number;
	currencyLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApServiceCdt { 
	key:string;
	serviceKey:string;
	cdtKey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	description:string;
} 

export interface ApSnomedCode { 
	key:string;
	version:string;
	code:string;
	description:string;
	semantictag:string;
	hyperLink:string;
	moreSpecification:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApTenant { 
	key:string;
	tenantId:string;
	tenantName:string;
	tenantType:string;
	tenantRegistrationDate:Date;
	tenantExpiryDate:Date;
	tenantEmailAddress:string;
	tenantBriefDesc:string;
	tenantSecurityToken:string;
	tenantDataGlobal:boolean;
	tenantSchemaName:string;
	tenantDbConnstr:string;
	tenantDbAdminUser:string;
	tenantLogoPath:string;
	tenantBackgroundPath:string;
	tenantSlogan:string;
	tenantLoginText:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApToothAction { 
	key:string;
	toothKey:string;
	actionKey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	note:string;
	surfaceLkey:string;
	existing:boolean;
	imageName:string;
	toothNumber:string;
} 

export interface ApToothActionLog { 
	key:string;
	toothKey:string;
	actionKey:string;
	logType:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	logTime:number;
	logOwner:string;
} 

export interface ApToothCdt { 
	key:string;
	toothKey:string;
	cdtKey:string;
	source:string;
	sourceKey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	surfaceLkey:string;
} 

export interface ApToothService { 
	key:string;
	toothKey:string;
	serviceKey:string;
	source:string;
	sourceKey:string;
	price:number;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApTranslation { 
	key:string;
	languageKey:string;
	translationFor:string;
	wordKey:string;
	originalText:string;
	translationText:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApUomGroups { 
	key:string;
	description:string;
	baseUom:string;
	uomEntries:number;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApUser { 
	key:string;
	username:string;
	password:string;
	fullName:string;
	verified:string;
	lastGeneratedOtp:string;
	passcode:string;
	tenantKey:string;
	organizationKey:string;
	accessRoleKey:string;
	email:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	departmentKey:string;
	firstName:string;
	secondName:string;
	lastName:string;
	dob:Date;
	sexAtBirthLkey:string;
	phoneNumber:number;
	jobDescription:string;
	jobRoleLkey:string;
	jobRoleKey:string;
	mustChangePassword:boolean;
} 

export interface ApUserFacilities { 
	key:string;
	userId:string;
	facilityId:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	userKey:string;
	facilityKey:string;
} 

export interface ApUserFacilitiyDepartments { 
	key:string;
	userKey:string;
	facilitiyKey:string;
	departmentKey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApUserMedicalLicense { 
	key:string;
	licenseName:string;
	licenseNumber:string;
	validTo:Date;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	userKey:string;
} 

