import * as modelTypes from "./model-types";
export const newApAccessRole:modelTypes.ApAccessRole = { 
	key:undefined,
	name:'',
	description:'',
	accessLevel:0,
	passwordErrorRetires:0,
	passwordExpires:undefined,
	passwordExpiresAfterDays:0,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApAccessRoleAuthorization:modelTypes.ApAccessRoleAuthorization = { 
	key:undefined,
	accessRoleKey:undefined,
	authorizationType:'',
	authorizationObjectKey:undefined,
	authorizationLevel:0,
	accessLevel:0,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApAccessRoleScreen:modelTypes.ApAccessRoleScreen = { 
	key:undefined,
	accessRoleKey:undefined,
	screenKey:undefined,
	canRead:undefined,
	canWrite:undefined,
	canDelete:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApAccessToken:modelTypes.ApAccessToken = { 
	key:undefined,
	userKey:undefined,
	canExpire:undefined,
	expiresAt:0,
	accessToken:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApActiveIngredient:modelTypes.ApActiveIngredient = { 
	key:undefined,
	code:'',
	name:'',
	hasSalt:undefined,
	saltLkey:undefined,
	medicalCategoryLkey:undefined,
	isControlled:undefined,
	controlledLkey:undefined,
	hasSynonyms:undefined,
	chemicalFormula:'',
	drugTypeLkey:undefined,
	drugClassLkey:undefined,
	hasBlackBoxWarning:undefined,
	blackBoxWarning:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
	mechanismOfAction:'',
	toxicityMaximumDose:'',
	toxicityMaximumDosePerUnitLkey:undefined,
	toxicityDetails:'',
	pregnancyCategoryLkey:undefined,
	pregnancyNotes:'',
	lactationRiskLkey:undefined,
	lactationRiskNotes:'',
	doseAdjustmentRenal:undefined,
	doseAdjustmentHepatic:undefined,
	pharmaAbsorption:'',
	pharmaRouteOfElimination:'',
	pharmaVolumeOfDistribution:'',
	pharmaHalfLife:'',
	pharmaProteinBinding:'',
	pharmaClearance:'',
	pharmaMetabolism:'',
	doseAdjPugA:'',
	doseAdjPugB:'',
	doseAdjPugC:'',
	doseAdjRenalOne:'',
	doseAdjRenalTwo:'',
	doseAdjRenalThree:'',
	doseAdjRenalFour:'',
} 

export const newApActiveIngredientAdverseEffect:modelTypes.ApActiveIngredientAdverseEffect = { 
	key:undefined,
	activeIngredientKey:undefined,
	adverseEffectLkey:undefined,
	isOther:undefined,
	otherDescription:'',
	typeLkey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApActiveIngredientContraindication:modelTypes.ApActiveIngredientContraindication = { 
	key:undefined,
	activeIngredientKey:undefined,
	contraindication:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApActiveIngredientDrugInteraction:modelTypes.ApActiveIngredientDrugInteraction = { 
	key:undefined,
	activeIngredientKey:undefined,
	interactedActiveIngredientKey:undefined,
	severityLkey:undefined,
	description:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApActiveIngredientFoodInteraction:modelTypes.ApActiveIngredientFoodInteraction = { 
	key:undefined,
	activeIngredientKey:undefined,
	foodDescription:'',
	severityLkey:undefined,
	description:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApActiveIngredientIndication:modelTypes.ApActiveIngredientIndication = { 
	key:undefined,
	activeIngredientKey:undefined,
	indication:'',
	isOffLabel:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApActiveIngredientRecommendedDosage:modelTypes.ApActiveIngredientRecommendedDosage = { 
	key:undefined,
	activeIngredientKey:undefined,
	indicationLkey:undefined,
	variableLkey:undefined,
	dosage:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApActiveIngredientSpecialPopulation:modelTypes.ApActiveIngredientSpecialPopulation = { 
	key:undefined,
	activeIngredientKey:undefined,
	additionalPopulationLkey:undefined,
	considerations:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApActiveIngredientSynonym:modelTypes.ApActiveIngredientSynonym = { 
	key:undefined,
	activeIngredientKey:undefined,
	synonym:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApAddresses:modelTypes.ApAddresses = { 
	key:undefined,
	entityId:'',
	entityTypeLkey:undefined,
	addressTypeLkey:undefined,
	streetAddressLine1:'',
	streetAddressLine2:'',
	countryLkey:undefined,
	stateProvinceRegionLkey:undefined,
	cityLkey:undefined,
	postalCode:'',
	additionalInfo:'',
	latitude:'',
	longitude:'',
	isActive:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApAgeGroup:modelTypes.ApAgeGroup = { 
	key:undefined,
	ageGroupLkey:undefined,
	fromAge:0,
	toAge:0,
	fromAgeUnitLkey:undefined,
	toAgeUnitLkey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApAllergens:modelTypes.ApAllergens = { 
	key:undefined,
	allergenCode:'',
	allergenName:'',
	allergenTypeLkey:undefined,
	description:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApAttachment:modelTypes.ApAttachment = { 
	key:undefined,
	attachmentType:'',
	referenceObjectKey:undefined,
	extraDetails:'',
	fileName:'',
	contentType:'',
	fileContent:new Uint8Array(),
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
	details:'',
	accessTypeLkey:undefined,
} 

export const newApCatalogDiagnosticTest:modelTypes.ApCatalogDiagnosticTest = { 
	key:undefined,
	testKey:undefined,
	catalogKey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApCdt:modelTypes.ApCdt = { 
	key:undefined,
	typeLkey:undefined,
	cdtCode:'',
	description:'',
	classLkey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApCdtDentalAction:modelTypes.ApCdtDentalAction = { 
	key:undefined,
	dentalActionKey:undefined,
	cdtKey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApClinicalDocumentation:modelTypes.ApClinicalDocumentation = { 
	key:undefined,
	patientKey:undefined,
	encounterKey:undefined,
	docTypeLkey:undefined,
	docCategoryLkey:undefined,
	docContent:'',
	userKey:undefined,
	userRoleLkey:undefined,
	facilityKey:undefined,
	docStatusLkey:undefined,
	docFormTypeKey:undefined,
	docFormKey:undefined,
	createdDatetime:null,
	approvedDatetime:null,
	approvedByUserKey:undefined,
	approvedByUserRoleLkey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApDentalAction:modelTypes.ApDentalAction = { 
	key:undefined,
	description:'',
	type:'',
	imageName:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
	favorite:undefined,
} 

export const newApDentalChart:modelTypes.ApDentalChart = { 
	key:undefined,
	encounterKey:undefined,
	patientKey:undefined,
	chartDate:null,
	type:'',
	chartSequence:0,
	status:'',
	treatmentPlan:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApDentalChartProgressNote:modelTypes.ApDentalChartProgressNote = { 
	key:undefined,
	chartKey:undefined,
	note:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApDentalChartTooth:modelTypes.ApDentalChartTooth = { 
	key:undefined,
	chartKey:undefined,
	toothNumber:'',
	missing:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
	toothNumberNumeric:0,
} 

export const newApDentalPlannedTreatment:modelTypes.ApDentalPlannedTreatment = { 
	key:undefined,
	patientKey:undefined,
	encounterKey:undefined,
	type:'',
	visitNumber:0,
	cdtKey:undefined,
	toothKey:undefined,
	note:'',
	surfaceLkey:undefined,
	billingTypeLkey:undefined,
	fees:0,
	insurance:0,
	discount:0,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
	statusLkey:undefined,
	source:'',
	sourceKey:undefined,
} 

export const newApDepartment:modelTypes.ApDepartment = { 
	key:undefined,
	facilityKey:undefined,
	name:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
	departmentTypeLkey:undefined,
	appointable:undefined,
	hasTriage:undefined,
	departmentCode:'',
} 

export const newApDiagnosticTest:modelTypes.ApDiagnosticTest = { 
	key:undefined,
	testTypeLkey:undefined,
	testName:'',
	internalCode:'',
	internationalCodeOne:'',
	internationalCodeTwo:'',
	internationalCodeThree:'',
	ageSpecific:undefined,
	genderSpecific:undefined,
	genderLkey:undefined,
	specialPopulation:undefined,
	price:0,
	currencyLkey:undefined,
	specialNotes:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApDiagnosticTestAgeType:modelTypes.ApDiagnosticTestAgeType = { 
	key:undefined,
	testKey:undefined,
	ageFrom:0,
	ageTo:0,
	ageTypeLkey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApDiagnosticTestCatalogHeader:modelTypes.ApDiagnosticTestCatalogHeader = { 
	key:undefined,
	description:'',
	typeLkey:undefined,
	departmentKey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
	testKey:undefined,
	catalogKey:undefined,
} 

export const newApDiagnosticTestEyeExam:modelTypes.ApDiagnosticTestEyeExam = { 
	key:undefined,
	testKey:undefined,
	eyeExamCategoryLkey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApDiagnosticTestGenetics:modelTypes.ApDiagnosticTestGenetics = { 
	key:undefined,
	testKey:undefined,
	internationalCodingTypeLkey:undefined,
	childCodeLkey:undefined,
	pathologyCategoryLkey:undefined,
	specimenTypeLkey:undefined,
	methodologyLkey:undefined,
	turnaroundTime:'',
	timeUnitLkey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApDiagnosticTestPathology:modelTypes.ApDiagnosticTestPathology = { 
	key:undefined,
	testKey:undefined,
	internationalCodingTypeLkey:undefined,
	childCodeLkey:undefined,
	pathologyCategoryLkey:undefined,
	specimenTypeLkey:undefined,
	analysisProcedureLkey:undefined,
	turnaroundTime:'',
	timeUnitLkey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApDiagnosticTestRadiology:modelTypes.ApDiagnosticTestRadiology = { 
	key:undefined,
	testKey:undefined,
	internationalCodingTypeLkey:undefined,
	childCodeLkey:undefined,
	radCategoryLkey:undefined,
	imageDuration:'',
	timeUnitLkey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
	labCatalogLkey:undefined,
	propertyLkey:undefined,
	systemLkey:undefined,
	scaleLkey:undefined,
	reagentsLkey:undefined,
	methodLkey:undefined,
	timingLkey:undefined,
	resultType:'',
	resultUnitLkey:undefined,
} 

export const newApDiagnosticTestSpecialPopulation:modelTypes.ApDiagnosticTestSpecialPopulation = { 
	key:undefined,
	testKey:undefined,
	specialPopulationLkey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApDvmRule:modelTypes.ApDvmRule = { 
	key:undefined,
	screenMetadataKey:undefined,
	ruleDescription:'',
	fieldKey:undefined,
	fieldName:'',
	fieldDataType:'',
	isFieldLov:undefined,
	isFieldRef:undefined,
	ruleType:'',
	ruleValue:'',
	ruleValueTwo:'',
	isDependant:undefined,
	dependantRuleCheck:'',
	dependantRuleKey:undefined,
	validationType:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApEncounter:modelTypes.ApEncounter = { 
	key:undefined,
	patientKey:undefined,
	patientFullName:'',
	patientAge:'',
	encounterStatusLkey:undefined,
	encounterClassLkey:undefined,
	encounterPriorityLkey:undefined,
	encounterTypeLkey:undefined,
	serviceTypeLkey:undefined,
	patientStatusLkey:undefined,
	episodeCareKey:undefined,
	basedOnLkey:undefined,
	basedOnKey:undefined,
	partOfEncounterKey:undefined,
	attendingPhysicianKey:undefined,
	responsiblePhysicianKey:undefined,
	facilityKey:undefined,
	appointmentKey:undefined,
	virtualService:undefined,
	plannedStartDate:null,
	plannedEndDate:null,
	actualStartDate:null,
	actualEndDate:null,
	actualLengthHrs:0,
	reasonLkey:undefined,
	primaryDiagnoseKey:undefined,
	dietPreferenceLkey:undefined,
	dietPreferenceText:'',
	valuableItemsText:'',
	specialArrangementLkey:undefined,
	specialArrangementText:'',
	specialCourtesyLkey:undefined,
	admissionOrigin:'',
	admissionSource:'',
	readmission:undefined,
	dischargeDestination:'',
	dischargeDisposition:'',
	locationTypeLkey:undefined,
	locationKey:undefined,
	followUpEncounterKey:undefined,
	queueNumber:0,
	billingAccountKey:undefined,
	paymentTypeLkey:undefined,
	payerTypeLkey:undefined,
	payerKey:undefined,
	insurancePlan:'',
	payerMemberId:'',
	referralNumber:'',
	accessLevel:0,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
	departmentKey:undefined,
	dischargeTypeLkey:undefined,
	actualLengthMinutes:0,
	chiefComplaint:'',
	hpiSummery:'',
	hpiKey:undefined,
	pastMedicalHistorySummery:'',
	pastMedicalHistoryKey:undefined,
	rosSummery:'',
	rosKey:undefined,
	assessmentSummery:'',
	assessmentKey:undefined,
	physicalExamSummery:'',
	physicalExamSummeryKey:undefined,
	progressNote:'',
	dischargeNote:'',
	dischargeSummery:'',
	visitId:'',
	encounterNotes:'',
	sourceName:'',
} 

export const newApEncounterAppliedService:modelTypes.ApEncounterAppliedService = { 
	key:undefined,
	encounterKey:undefined,
	serviceKey:undefined,
	categoryLkey:undefined,
	source:'',
	sourceKey:undefined,
	extraDetails:'',
	price:0,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

