import * as modelTypes from "./model-types";
export const newApAccessRole:modelTypes.ApAccessRole = { 
	key:undefined,
	name:'',
	description:'',
	accessLevel:0,
	passwordErrorRetires:0,
	passwordExpires:undefined,
	passwordExpiresAfterDays:0,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApAccessRoleAuthorization:modelTypes.ApAccessRoleAuthorization = { 
	key:undefined,
	accessRoleKey:undefined,
	authorizationType:'',
	authorizationObjectKey:undefined,
	authorizationLevel:0,
	accessLevel:0,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApAccessRoleScreen:modelTypes.ApAccessRoleScreen = { 
	key:undefined,
	accessRoleKey:undefined,
	screenKey:undefined,
	canRead:undefined,
	canWrite:undefined,
	canDelete:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApAccessToken:modelTypes.ApAccessToken = { 
	key:undefined,
	userKey:undefined,
	canExpire:undefined,
	expiresAt:0,
	accessToken:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApActiveIngredient:modelTypes.ApActiveIngredient = { 
	key:undefined,
	code:'',
	name:'',
	hasSalt:undefined,
	saltLkey:undefined,
	medicalCategoryLkey:undefined,
	isControlled:undefined,
	controlledLkey:undefined,
	hasSynonyms:undefined,
	chemicalFormula:'',
	drugTypeLkey:undefined,
	drugClassLkey:undefined,
	hasBlackBoxWarning:undefined,
	blackBoxWarning:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
	mechanismOfAction:'',
	toxicityMaximumDose:'',
	toxicityMaximumDosePerUnitLkey:undefined,
	toxicityDetails:'',
	pregnancyCategoryLkey:undefined,
	pregnancyNotes:'',
	lactationRiskLkey:undefined,
	lactationRiskNotes:'',
	doseAdjustmentRenal:undefined,
	doseAdjustmentHepatic:undefined,
	pharmaAbsorption:'',
	pharmaRouteOfElimination:'',
	pharmaVolumeOfDistribution:'',
	pharmaHalfLife:'',
	pharmaProteinBinding:'',
	pharmaClearance:'',
	pharmaMetabolism:'',
} 

export const newApActiveIngredientAdverseEffect:modelTypes.ApActiveIngredientAdverseEffect = { 
	key:undefined,
	activeIngredientKey:undefined,
	adverseEffectLkey:undefined,
	isOther:undefined,
	otherDescription:'',
	typeLkey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApActiveIngredientContraindication:modelTypes.ApActiveIngredientContraindication = { 
	key:undefined,
	activeIngredientKey:undefined,
	contraindication:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApActiveIngredientDrugInteraction:modelTypes.ApActiveIngredientDrugInteraction = { 
	key:undefined,
	activeIngredientKey:undefined,
	interactedActiveIngredientKey:undefined,
	severityLkey:undefined,
	description:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApActiveIngredientFoodInteraction:modelTypes.ApActiveIngredientFoodInteraction = { 
	key:undefined,
	activeIngredientKey:undefined,
	foodDescription:'',
	severityLkey:undefined,
	description:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApActiveIngredientIndication:modelTypes.ApActiveIngredientIndication = { 
	key:undefined,
	activeIngredientKey:undefined,
	indication:'',
	isOffLabel:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApActiveIngredientRecommendedDosage:modelTypes.ApActiveIngredientRecommendedDosage = { 
	key:undefined,
	activeIngredientKey:undefined,
	indicationLkey:undefined,
	variableLkey:undefined,
	dosage:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApActiveIngredientSpecialPopulation:modelTypes.ApActiveIngredientSpecialPopulation = { 
	key:undefined,
	activeIngredientKey:undefined,
	additionalPopulationLkey:undefined,
	considerations:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApActiveIngredientSynonym:modelTypes.ApActiveIngredientSynonym = { 
	key:undefined,
	activeIngredientKey:undefined,
	synonym:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApAddresses:modelTypes.ApAddresses = { 
	key:undefined,
	entityId:'',
	entityTypeLkey:undefined,
	addressTypeLkey:undefined,
	streetAddressLine1:'',
	streetAddressLine2:'',
	countryLkey:undefined,
	stateProvinceRegionLkey:undefined,
	cityLkey:undefined,
	postalCode:'',
	additionalInfo:'',
	latitude:'',
	longitude:'',
	isActive:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApAllergens:modelTypes.ApAllergens = { 
	key:undefined,
	allergenCode:'',
	allergenName:'',
	allergenTypeLkey:undefined,
	description:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApAttachment:modelTypes.ApAttachment = { 
	key:undefined,
	attachmentType:'',
	referenceObjectKey:undefined,
	extraDetails:'',
	fileName:'',
	contentType:'',
	fileContent:new Uint8Array(),
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
	details:'',
} 

export const newApCatalogDiagnosticTest:modelTypes.ApCatalogDiagnosticTest = { 
	key:undefined,
	testKey:undefined,
	catalogKey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApCdt:modelTypes.ApCdt = { 
	key:undefined,
	typeLkey:undefined,
	cdtCode:'',
	description:'',
	classLkey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApCdtDentalAction:modelTypes.ApCdtDentalAction = { 
	key:undefined,
	dentalActionKey:undefined,
	cdtKey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApClinicalDocumentation:modelTypes.ApClinicalDocumentation = { 
	key:undefined,
	patientKey:undefined,
	encounterKey:undefined,
	docTypeLkey:undefined,
	docCategoryLkey:undefined,
	docContent:'',
	userKey:undefined,
	userRoleLkey:undefined,
	facilityKey:undefined,
	docStatusLkey:undefined,
	docFormTypeKey:undefined,
	docFormKey:undefined,
	createdDatetime:null,
	approvedDatetime:null,
	approvedByUserKey:undefined,
	approvedByUserRoleLkey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApDentalAction:modelTypes.ApDentalAction = { 
	key:undefined,
	description:'',
	type:'',
	imageName:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
	favorite:undefined,
} 

export const newApDentalChart:modelTypes.ApDentalChart = { 
	key:undefined,
	encounterKey:undefined,
	patientKey:undefined,
	chartDate:null,
	type:'',
	chartSequence:0,
	status:'',
	treatmentPlan:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApDentalChartProgressNote:modelTypes.ApDentalChartProgressNote = { 
	key:undefined,
	chartKey:undefined,
	note:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApDentalChartTooth:modelTypes.ApDentalChartTooth = { 
	key:undefined,
	chartKey:undefined,
	toothNumber:'',
	missing:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
	toothNumberNumeric:0,
} 

export const newApDentalPlannedTreatment:modelTypes.ApDentalPlannedTreatment = { 
	key:undefined,
	patientKey:undefined,
	encounterKey:undefined,
	type:'',
	visitNumber:0,
	cdtKey:undefined,
	toothKey:undefined,
	note:'',
	surfaceLkey:undefined,
	billingTypeLkey:undefined,
	fees:0,
	insurance:0,
	discount:0,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
	statusLkey:undefined,
	source:'',
	sourceKey:undefined,
} 

export const newApDepartment:modelTypes.ApDepartment = { 
	key:undefined,
	facilityKey:undefined,
	name:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
	departmentTypeLkey:undefined,
	appointable:undefined,
	hasTriage:undefined,
	departmentCode:'',
} 

export const newApDiagnosticTest:modelTypes.ApDiagnosticTest = { 
	key:undefined,
	testTypeLkey:undefined,
	testName:'',
	internalCode:'',
	internationalCodeOne:'',
	internationalCodeTwo:'',
	internationalCodeThree:'',
	ageSpecific:undefined,
	genderSpecific:undefined,
	genderLkey:undefined,
	specialPopulation:undefined,
	price:0,
	currencyLkey:undefined,
	specialNotes:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApDiagnosticTestAgeType:modelTypes.ApDiagnosticTestAgeType = { 
	key:undefined,
	testKey:undefined,
	ageFrom:0,
	ageTo:0,
	ageTypeLkey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApDiagnosticTestCatalogHeader:modelTypes.ApDiagnosticTestCatalogHeader = { 
	key:undefined,
	description:'',
	typeLkey:undefined,
	departmentKey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
	testKey:undefined,
	catalogKey:undefined,
} 

export const newApDiagnosticTestEyeExam:modelTypes.ApDiagnosticTestEyeExam = { 
	key:undefined,
	testKey:undefined,
	eyeExamCategoryLkey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApDiagnosticTestGenetics:modelTypes.ApDiagnosticTestGenetics = { 
	key:undefined,
	testKey:undefined,
	internationalCodingTypeLkey:undefined,
	childCodeLkey:undefined,
	pathologyCategoryLkey:undefined,
	specimenTypeLkey:undefined,
	methodologyLkey:undefined,
	turnaroundTime:'',
	timeUnitLkey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApDiagnosticTestPathology:modelTypes.ApDiagnosticTestPathology = { 
	key:undefined,
	testKey:undefined,
	internationalCodingTypeLkey:undefined,
	childCodeLkey:undefined,
	pathologyCategoryLkey:undefined,
	specimenTypeLkey:undefined,
	analysisProcedureLkey:undefined,
	turnaroundTime:'',
	timeUnitLkey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApDiagnosticTestRadiology:modelTypes.ApDiagnosticTestRadiology = { 
	key:undefined,
	testKey:undefined,
	internationalCodingTypeLkey:undefined,
	childCodeLkey:undefined,
	radCategoryLkey:undefined,
	imageDuration:'',
	timeUnitLkey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApDiagnosticTestSpecialPopulation:modelTypes.ApDiagnosticTestSpecialPopulation = { 
	key:undefined,
	testKey:undefined,
	specialPopulationLkey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApDvmRule:modelTypes.ApDvmRule = { 
	key:undefined,
	screenMetadataKey:undefined,
	ruleDescription:'',
	fieldKey:undefined,
	fieldName:'',
	fieldDataType:'',
	isFieldLov:undefined,
	isFieldRef:undefined,
	ruleType:'',
	ruleValue:'',
	ruleValueTwo:'',
	isDependant:undefined,
	dependantRuleCheck:'',
	dependantRuleKey:undefined,
	validationType:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApEncounter:modelTypes.ApEncounter = { 
	key:undefined,
	patientKey:undefined,
	patientFullName:'',
	patientAge:'',
	encounterStatusLkey:undefined,
	encounterClassLkey:undefined,
	encounterPriorityLkey:undefined,
	encounterTypeLkey:undefined,
	serviceTypeLkey:undefined,
	patientStatusLkey:undefined,
	episodeCareKey:undefined,
	basedOnLkey:undefined,
	basedOnKey:undefined,
	partOfEncounterKey:undefined,
	attendingPhysicianKey:undefined,
	responsiblePhysicianKey:undefined,
	facilityKey:undefined,
	appointmentKey:undefined,
	virtualService:undefined,
	plannedStartDate:null,
	plannedEndDate:null,
	actualStartDate:null,
	actualEndDate:null,
	actualLengthHrs:0,
	reasonLkey:undefined,
	primaryDiagnoseKey:undefined,
	dietPreferenceLkey:undefined,
	dietPreferenceText:'',
	valuableItemsText:'',
	specialArrangementLkey:undefined,
	specialArrangementText:'',
	specialCourtesyLkey:undefined,
	admissionOrigin:'',
	admissionSource:'',
	readmission:undefined,
	dischargeDestination:'',
	dischargeDisposition:'',
	locationTypeLkey:undefined,
	locationKey:undefined,
	followUpEncounterKey:undefined,
	queueNumber:0,
	billingAccountKey:undefined,
	paymentTypeLkey:undefined,
	payerTypeLkey:undefined,
	payerKey:undefined,
	insurancePlan:'',
	payerMemberId:'',
	referralNumber:'',
	accessLevel:0,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
	departmentKey:undefined,
	dischargeTypeLkey:undefined,
	actualLengthMinutes:0,
	chiefComplaint:'',
	hpiSummery:'',
	hpiKey:undefined,
	pastMedicalHistorySummery:'',
	pastMedicalHistoryKey:undefined,
	rosSummery:'',
	rosKey:undefined,
	assessmentSummery:'',
	assessmentKey:undefined,
	physicalExamSummery:'',
	physicalExamSummeryKey:undefined,
	progressNote:'',
	dischargeNote:'',
	dischargeSummery:'',
	visitId:'',
} 

export const newApEncounterAppliedService:modelTypes.ApEncounterAppliedService = { 
	key:undefined,
	encounterKey:undefined,
	serviceKey:undefined,
	categoryLkey:undefined,
	source:'',
	sourceKey:undefined,
	extraDetails:'',
	price:0,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApFacility:modelTypes.ApFacility = { 
	key:undefined,
	facilityId:'',
	facilityName:'',
	facilityNameOtherLang:'',
	tenantId:'',
	facilityRegistrationDate:null,
	facilityEmailAddress:'',
	facilityBriefDesc:'',
	facilityAddressOtherLang:'',
	facilityLogoFile:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
	facilityPhone1:'',
	facilityPhone2:'',
	facilityFax:'',
	facilityAddressId:'',
	facilityTypeLkey:undefined,
	facilityType:'',
	facilityAddress:'',
} 

export const newApGenericMedication:modelTypes.ApGenericMedication = { 
	key:undefined,
	genericName:'',
	manufacturerLkey:undefined,
	usageInstructions:'',
	roaLkey:undefined,
	dosageFormLkey:undefined,
	expiresAfterOpening:undefined,
	expiresAfterOpeningValue:'',
	singlePatientUse:undefined,
	price:0,
	currencyLkey:undefined,
	priceListKey:undefined,
	cost:0,
	storageRequirements:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApGlobalSettings:modelTypes.ApGlobalSettings = { 
	key:undefined,
	facilityKey:undefined,
	settingKey:undefined,
	settingValue:'',
	settingCategory:'',
	requireRestart:undefined,
	requirePasscode:undefined,
	fixedValue:undefined,
	forAdminUse:undefined,
	hiddenSetting:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApIcdCode:modelTypes.ApIcdCode = { 
	key:undefined,
	icdVersion:'',
	icdCode:'',
	description:'',
	chapter:'',
	block:'',
	category:'',
	subcategory:'',
	fulldescription:'',
	includes:'',
	excludes1:'',
	excludes2:'',
	useadditionalcode:'',
	codefirst:'',
	codingguidelines:'',
	clinicaldescription:'',
	severity:'',
	synonyms:'',
	abbreviations:'',
	notes:'',
	requireSide:'',
	requireDetails:'',
	linkedWithAge:'',
	linkedWithGender:'',
	linkedWithDisease:'',
	moreSpecification:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApLanguages:modelTypes.ApLanguages = { 
	key:undefined,
	languageCode:'',
	languageName:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApLicense:modelTypes.ApLicense = { 
	key:undefined,
	tenantId:'',
	licenseId:'',
	licenseKey:undefined,
	licenseType:'',
	startDate:null,
	endDate:null,
	activestatus:undefined,
	uuidHwKeys:undefined,
	facilityAddress:'',
	facilityLogoFile:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApLicenseDetails:modelTypes.ApLicenseDetails = { 
	key:undefined,
	tenantId:'',
	licenseId:'',
	facilityCount:0,
	bedCount:0,
	userCount:0,
	modules:'',
	facilityUsageCount:0,
	bedUsageCount:0,
	userUsageCount:0,
	lastUsageDate:null,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApLov:modelTypes.ApLov = { 
	key:undefined,
	lovCode:'',
	lovName:'',
	lovDescription:'',
	loveCustomCode:'',
	parentLov:'',
	autoSelectDefault:undefined,
	defaultValueId:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApLovValues:modelTypes.ApLovValues = { 
	key:undefined,
	lovKey:undefined,
	lovCode:'',
	valueCode:'',
	lovDisplayVale:'',
	loveCustomCode:'',
	valueDescription:'',
	valueColor:0,
	valueIcon:'',
	valueOrder:0,
	isdefault:undefined,
	seededData:undefined,
	forInternalUser:undefined,
	specificForScreenId:'',
	parentValueId:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApMessages:modelTypes.ApMessages = { 
	key:undefined,
	messageId:'',
	messageCode:'',
	messageType:'',
	messageHeader:'',
	messageText:'',
	languageCode:'',
	isoriginalMessage:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApMetadata:modelTypes.ApMetadata = { 
	key:undefined,
	objectName:'',
	dbObjectName:'',
	description:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApMetadataField:modelTypes.ApMetadataField = { 
	key:undefined,
	fieldName:'',
	dbFieldName:'',
	metadataKey:undefined,
	dbObjectName:'',
	dataType:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApModule:modelTypes.ApModule = { 
	key:undefined,
	name:'',
	description:'',
	iconImagePath:'',
	viewOrder:0,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApPatient:modelTypes.ApPatient = { 
	key:undefined,
	patientMrn:'',
	namePrefix:'',
	nameSuffix:'',
	patientAlias:'',
	firstName:'',
	secondName:'',
	thirdName:'',
	lastName:'',
	fullName:'',
	secondNameOtherLang:'',
	firstNameOtherLang:'',
	thirdNameOtherLang:'',
	lastNameOtherLang:'',
	fullNameOtherLang:'',
	documentCountryLkey:undefined,
	documentTypeLkey:undefined,
	documentNo:'',
	noDocument:undefined,
	specialCourtesyLkey:undefined,
	unknown:'',
	genderLkey:undefined,
	phoneNumber:'',
	mobileNumber:'',
	email:'',
	maritalStatusLkey:undefined,
	nationalityLkey:undefined,
	primaryLanguageLkey:undefined,
	religionLkey:undefined,
	ethnicityLkey:undefined,
	occupationLkey:undefined,
	emergencyContactName:'',
	emergencyContactRelationLkey:undefined,
	emergencyContactPhone:'',
	streetAddressLine1:'',
	streetAddressLine2:'',
	countryLkey:undefined,
	stateProvinceRegionLkey:undefined,
	cityLkey:undefined,
	postalCode:'',
	additionalInfo:'',
	latitude:0,
	longitude:'',
	isActive:'',
	deathDatetime:null,
	dob:null,
	multipleBirth:undefined,
	birthOrder:0,
	numSiblings:0,
	accessLevel:0,
	facilityKey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
	patientClassLkey:undefined,
	privatePatient:undefined,
	verificationOtp:'',
	securityAccessLevelLkey:undefined,
	socialSecurityNumber:'',
	noticeOfPrivacyPractice:undefined,
	noticeOfPrivacyPracticeDate:null,
	privacyAuthorization:undefined,
	privacyAuthorizationDate:null,
	consent:undefined,
	consentDate:null,
	verified:undefined,
	responsiblePartyLkey:undefined,
	educationalLevelLkey:undefined,
	previousId:'',
	archivingNumber:'',
	receiveSms:undefined,
	receiveEmail:undefined,
	homePhone:'',
	workPhone:'',
	preferredContactLkey:undefined,
	unknownPatient:undefined,
	incompletePatient:undefined,
	extraDetails:'',
	secondaryMobileNumber:'',
} 

export const newApPatientAddresses:modelTypes.ApPatientAddresses = { 
	key:undefined,
	patientKey:undefined,
	addressTypeLkey:undefined,
	streetAddressLine1:'',
	streetAddressLine2:'',
	countryLkey:undefined,
	stateProvinceRegionLkey:undefined,
	cityLkey:undefined,
	postalCode:'',
	additionalInfo:'',
	latitude:0,
	longitude:'',
	isActive:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApPatientAlerts:modelTypes.ApPatientAlerts = { 
	key:undefined,
	patientKey:undefined,
	alertTypeLkey:undefined,
	alertSourceLkey:undefined,
	alertDescription:'',
	alertSeverityLkey:undefined,
	isResolved:undefined,
	alertDate:null,
	dateResolved:null,
	notes:'',
	sourceOfInfoLkey:undefined,
	sourceKey:undefined,
	lifeThreating:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApPatientAllergies:modelTypes.ApPatientAllergies = { 
	key:undefined,
	patientKey:undefined,
	allergyKey:undefined,
	allergenTypeLkey:undefined,
	severityLkey:undefined,
	reaction:'',
	dateDiagnosed:null,
	resolutionStatusLkey:undefined,
	dateResolved:null,
	treatmentPlan:'',
	notes:'',
	sourceOfInfoLkey:undefined,
	lifeThreating:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
	addedByVisitKey:undefined,
} 

export const newApPatientDiagnose:modelTypes.ApPatientDiagnose = { 
	key:undefined,
	patientKey:undefined,
	visitKey:undefined,
	diagnoseCode:'',
	description:'',
	diagnoseCodingLkey:undefined,
	dateDiagnosed:null,
	onsetDate:null,
	diagnoseStatusLkey:undefined,
	diagnoseTypeLkey:undefined,
	diagnoseSiteLkey:undefined,
	providerTypeLkey:undefined,
	providerLkey:undefined,
	providerUserName:'',
	providerRoleLkey:undefined,
	notes:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApPatientIds:modelTypes.ApPatientIds = { 
	key:undefined,
	patientKey:undefined,
	identifierTypeLovKey:undefined,
	identifierCode:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApPatientInsurance:modelTypes.ApPatientInsurance = { 
	key:undefined,
	patientKey:undefined,
	insuranceProviderLkey:undefined,
	primaryInsurance:undefined,
	insurancePolicyNumber:'',
	groupNumber:'',
	insurancePlanTypeLkey:undefined,
	authorizationNumbers:'',
	expirationDate:null,
	coPayment:undefined,
	coPaymentValue:0,
	coInsurance:undefined,
	coInsuranceValue:0,
	deductibles:undefined,
	deductiblesValue:0,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
	policyHolder:'',
} 

export const newApPatientInsuranceCoverage:modelTypes.ApPatientInsuranceCoverage = { 
	key:undefined,
	patientInsuranceKey:undefined,
	typeLkey:undefined,
	coverageTypeLkey:undefined,
	coveredAmount:0,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApPatientObservation:modelTypes.ApPatientObservation = { 
	key:undefined,
	patientKey:undefined,
	visitKey:undefined,
	observationDate:null,
	observationTypeLkey:undefined,
	value:'',
	value2:'',
	unitofMeasureLkey:undefined,
	referencerangeLkey:undefined,
	statusLkey:undefined,
	methodLkey:undefined,
	positionLkey:undefined,
	siteLkey:undefined,
	equipmentUsedLkey:undefined,
	comments:'',
	sourceRecordKey:undefined,
	providerKey:undefined,
	providerName:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApPatientObservationSummary:modelTypes.ApPatientObservationSummary = { 
	key:undefined,
	patientKey:undefined,
	visitKey:undefined,
	lastDate:null,
	latesttemperature:0,
	latestbpSystolic:0,
	latestbpDiastolic:0,
	latestheartrate:0,
	latestrespiratoryrate:0,
	latestoxygensaturation:0,
	latestglucoselevel:0,
	latestpainlevel:0,
	latestweight:0,
	latestheight:0,
	latestheadcircumference:0,
	latestlength:0,
	latestbmi:0,
	age:0,
	prevRecordKey:undefined,
	plastDate:null,
	platesttemperature:0,
	platestbpSystolic:0,
	platestbpDiastolic:0,
	platestheartrate:0,
	platestrespiratoryrate:0,
	platestoxygensaturation:0,
	platestglucoselevel:0,
	platestpainlevel:0,
	platestweight:0,
	platestheight:0,
	platestheadcircumference:0,
	platestlength:0,
	platestbmi:0,
	page:0,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApPatientProblem:modelTypes.ApPatientProblem = { 
	key:undefined,
	patientKey:undefined,
	problemCode:'',
	description:'',
	problemCodingLkey:undefined,
	dateDiagnosed:null,
	problemStatusLkey:undefined,
	severityLkey:undefined,
	onSetDate:null,
	providerTypeLkey:undefined,
	providerLkey:undefined,
	providerUserName:'',
	providerRoleLkey:undefined,
	resolvedDate:null,
	dateAdded:null,
	notes:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApPatientRelation:modelTypes.ApPatientRelation = { 
	key:undefined,
	patientKey:undefined,
	relativePatientKey:undefined,
	relationTypeLkey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApPatientSecondaryDocuments:modelTypes.ApPatientSecondaryDocuments = { 
	key:undefined,
	documentCountryLkey:undefined,
	documentTypeLkey:undefined,
	documentNo:'',
	patientKey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApPhysicalExamArea:modelTypes.ApPhysicalExamArea = { 
	key:undefined,
	patientKey:undefined,
	encounterKey:undefined,
	physicalExamAreaLkey:undefined,
	physicalExamAreaDetailLkey:undefined,
	notes:'',
	sourceOfAnswerLkey:undefined,
	pass:undefined,
	passReasonLkey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApPractitioner:modelTypes.ApPractitioner = { 
	key:undefined,
	primaryFacilityKey:undefined,
	practitionerFullName:'',
	genderLkey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
	departmentKey:undefined,
} 

export const newApPrescriptionInstruction:modelTypes.ApPrescriptionInstruction = { 
	key:undefined,
	categoryLkey:undefined,
	dose:0,
	unitLkey:undefined,
	routLkey:undefined,
	frequencyLkey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApReviewOfSystem:modelTypes.ApReviewOfSystem = { 
	key:undefined,
	patientKey:undefined,
	encounterKey:undefined,
	systemLkey:undefined,
	systemDetailLkey:undefined,
	notes:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApScreen:modelTypes.ApScreen = { 
	key:undefined,
	name:'',
	description:'',
	moduleKey:undefined,
	iconImagePath:'',
	viewOrder:0,
	navPath:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApScreenMetadata:modelTypes.ApScreenMetadata = { 
	key:undefined,
	screenKey:undefined,
	metadataKey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApService:modelTypes.ApService = { 
	key:undefined,
	typeLkey:undefined,
	name:'',
	abbreviation:'',
	code:'',
	categoryLkey:undefined,
	price:0,
	currencyLkey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApServiceCdt:modelTypes.ApServiceCdt = { 
	key:undefined,
	serviceKey:undefined,
	cdtKey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
	description:'',
} 

export const newApSnomedCode:modelTypes.ApSnomedCode = { 
	key:undefined,
	version:'',
	code:'',
	description:'',
	semantictag:'',
	hyperLink:'',
	moreSpecification:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApTenant:modelTypes.ApTenant = { 
	key:undefined,
	tenantId:'',
	tenantName:'',
	tenantType:'',
	tenantRegistrationDate:null,
	tenantExpiryDate:null,
	tenantEmailAddress:'',
	tenantBriefDesc:'',
	tenantSecurityToken:'',
	tenantDataGlobal:undefined,
	tenantSchemaName:'',
	tenantDbConnstr:'',
	tenantDbAdminUser:'',
	tenantLogoPath:'',
	tenantBackgroundPath:'',
	tenantSlogan:'',
	tenantLoginText:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApToothAction:modelTypes.ApToothAction = { 
	key:undefined,
	toothKey:undefined,
	actionKey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
	note:'',
	surfaceLkey:undefined,
	existing:undefined,
	imageName:'',
	toothNumber:'',
} 

export const newApToothActionLog:modelTypes.ApToothActionLog = { 
	key:undefined,
	toothKey:undefined,
	actionKey:undefined,
	logType:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
	logTime:0,
	logOwner:'',
} 

export const newApToothCdt:modelTypes.ApToothCdt = { 
	key:undefined,
	toothKey:undefined,
	cdtKey:undefined,
	source:'',
	sourceKey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
	surfaceLkey:undefined,
} 

export const newApToothService:modelTypes.ApToothService = { 
	key:undefined,
	toothKey:undefined,
	serviceKey:undefined,
	source:'',
	sourceKey:undefined,
	price:0,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApTranslation:modelTypes.ApTranslation = { 
	key:undefined,
	languageKey:undefined,
	translationFor:'',
	wordKey:undefined,
	originalText:'',
	translationText:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApUomGroups:modelTypes.ApUomGroups = { 
	key:undefined,
	description:'',
	baseUom:'',
	uomEntries:0,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApUser:modelTypes.ApUser = { 
	key:undefined,
	username:'',
	password:'',
	fullName:'',
	verified:'',
	lastGeneratedOtp:'',
	passcode:'',
	tenantKey:undefined,
	organizationKey:undefined,
	accessRoleKey:undefined,
	email:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
	departmentKey:undefined,
	firstName:'',
	secondName:'',
	lastName:'',
	dob:null,
	sexAtBirthLkey:undefined,
	phoneNumber:0,
	jobDescription:'',
	jobRoleLkey:undefined,
	jobRoleKey:undefined,
	mustChangePassword:undefined,
} 

export const newApUserFacilities:modelTypes.ApUserFacilities = { 
	key:undefined,
	userId:'',
	facilityId:'',
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
	userKey:undefined,
	facilityKey:undefined,
} 

export const newApUserFacilitiyDepartments:modelTypes.ApUserFacilitiyDepartments = { 
	key:undefined,
	userKey:undefined,
	facilitiyKey:undefined,
	departmentKey:undefined,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
} 

export const newApUserMedicalLicense:modelTypes.ApUserMedicalLicense = { 
	key:undefined,
	licenseName:'',
	licenseNumber:'',
	validTo:null,
	createdBy:'',
	updatedBy:'',
	deletedBy:'',
	createdAt:undefined,
	updatedAt:undefined,
	deletedAt:undefined,
	isValid:undefined,
	userKey:undefined,
} 

