export interface ApAccessRole { 
	key:string;
	name:string;
	description:string;
	accessLevel:number;
	passwordErrorRetires:number;
	passwordExpires:boolean;
	passwordExpiresAfterDays:number;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApAccessRoleAuthorization { 
	key:string;
	accessRoleKey:string;
	authorizationType:string;
	authorizationObjectKey:string;
	authorizationLevel:number;
	accessLevel:number;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApAccessRoleScreen { 
	key:string;
	accessRoleKey:string;
	screenKey:string;
	canRead:boolean;
	canWrite:boolean;
	canDelete:boolean;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApAccessToken { 
	key:string;
	userKey:string;
	canExpire:boolean;
	expiresAt:number;
	accessToken:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApActiveIngredient { 
	key:string;
	code:string;
	name:string;
	hasSalt:boolean;
	saltLkey:string;
	medicalCategoryLkey:string;
	isControlled:boolean;
	controlledLkey:string;
	hasSynonyms:boolean;
	atcCode:string;
	drugTypeLkey:string;
	drugClassLkey:string;
	hasBlackBoxWarning:boolean;
	blackBoxWarning:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	mechanismOfAction:string;
	toxicityMaximumDose:string;
	toxicityMaximumDosePerUnitLkey:string;
	toxicityDetails:string;
	pregnancyCategoryLkey:string;
	pregnancyNotes:string;
	lactationRiskLkey:string;
	lactationRiskNotes:string;
	doseAdjustmentRenal:boolean;
	doseAdjustmentHepatic:boolean;
	pharmaAbsorption:string;
	pharmaRouteOfElimination:string;
	pharmaVolumeOfDistribution:string;
	pharmaHalfLife:string;
	pharmaProteinBinding:string;
	pharmaClearance:string;
	pharmaMetabolism:string;
	doseAdjPugA:string;
	doseAdjPugB:string;
	doseAdjPugC:string;
	doseAdjRenalOne:string;
	doseAdjRenalTwo:string;
	doseAdjRenalThree:string;
	doseAdjRenalFour:string;
	chemicalFormula:string;
} 

export interface ApActiveIngredientAdverseEffect { 
	key:string;
	activeIngredientKey:string;
	adverseEffectLkey:string;
	isOther:boolean;
	otherDescription:string;
	typeLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApActiveIngredientContraindication { 
	key:string;
	activeIngredientKey:string;
	contraindication:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	icdCodeKey:string;
} 

export interface ApActiveIngredientDrugInteraction { 
	key:string;
	activeIngredientKey:string;
	interactedActiveIngredientKey:string;
	severityLkey:string;
	description:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApActiveIngredientFoodInteraction { 
	key:string;
	activeIngredientKey:string;
	foodDescription:string;
	severityLkey:string;
	description:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApActiveIngredientIndication { 
	key:string;
	activeIngredientKey:string;
	indication:string;
	isOffLabel:boolean;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	icdCodeKey:string;
} 

export interface ApActiveIngredientRecommendedDosage { 
	key:string;
	activeIngredientKey:string;
	indicationLkey:string;
	variableLkey:string;
	dosage:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApActiveIngredientSpecialPopulation { 
	key:string;
	activeIngredientKey:string;
	additionalPopulationLkey:string;
	considerations:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApActiveIngredientSynonym { 
	key:string;
	activeIngredientKey:string;
	synonym:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApAddresses { 
	key:string;
	entityId:string;
	entityTypeLkey:string;
	addressTypeLkey:string;
	streetAddressLine1:string;
	streetAddressLine2:string;
	countryLkey:string;
	stateProvinceRegionLkey:string;
	cityLkey:string;
	postalCode:string;
	additionalInfo:string;
	latitude:string;
	longitude:string;
	isActive:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApAdmitOutpatientInpatient { 
	key:string;
	toEncounterKey:string;
	fromEncounterKey:string;
	inpatientDepartmentKey:string;
	physicianKey:string;
	admissionNotes:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	admitSourceLkey:string;
	admissionDepartmentKey:string;
	roomKey:string;
	bedKey:string;
	handoffInformation:string;
	icd10:string;
	reasonOfAdmission:string;
} 

export interface ApAgeGroup { 
	key:string;
	ageGroupLkey:string;
	fromAge:number;
	toAge:number;
	fromAgeUnitLkey:string;
	toAgeUnitLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApAllergens { 
	key:string;
	allergenCode:string;
	allergenName:string;
	allergenTypeLkey:string;
	description:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApAppointment { 
	key:string;
	patientKey:string;
	facilityKey:string;
	resourceTypeLkey:string;
	resourceKey:string;
	visitTypeLkey:string;
	durationLkey:string;
	appointmentStart:string;
	appointmentEnd:string;
	instructions:string;
	notes:string;
	priorityLkey:string;
	isReminder:string;
	reminderLkey:string;
	consentForm:string;
	referingPhysicianLkey:string;
	externalPhysician:string;
	procedureLevelLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	resourceLkey:string;
	instructionsLkey:string;
	appointmentStatus:string;
	reasonLkey:string;
	reasonValue:string;
	otherReason:string;
	noShowReasonLkey:string;
	noShowReasonValue:string;
	noShowOtherReason:string;
} 

export interface ApAttachment { 
	key:string;
	attachmentType:string;
	referenceObjectKey:string;
	extraDetails:string;
	fileName:string;
	contentType:string;
	fileContent:uint8array;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	details:string;
	accessTypeLkey:string;
	patientKey:string;
} 

export interface ApAudiometryPuretone { 
	key:string;
	patientKey:string;
	encounterKey:string;
	testEnvironment:string;
	testReason:string;
	earExamFindingsLkey:string;
	airConductionFrequenciesLeft:number;
	airConductionFrequenciesRight:number;
	hearingThresholdsLeft:number;
	hearingThresholdsRight:number;
	boneConductionFrequenciesLeft:number;
	boneConductionFrequenciesRight:number;
	boneConductionThresholdsLeft:number;
	boneConductionThresholdsRight:number;
	maskedUsed:boolean;
	hearingLossTypeLkey:string;
	hearingLossDegreeLkey:string;
	recommendations:string;
	additionalNotes:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	cancellationReason:string;
	statusLkey:string;
} 

export interface ApBed { 
	key:string;
	roomKey:string;
	name:string;
	bedTypeLkey:string;
	locationDetails:string;
	isValid:boolean;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	statusLkey:string;
} 

export interface ApBedTransactions { 
	key:string;
	encounterKey:string;
	patientKey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	fromRoomKey:string;
	fromBedKey:string;
	toRoomKey:string;
	toBedKey:string;
	departmentKey:string;
} 

export interface ApBrandMedicationSubstitutes { 
	key:string;
	brandKey:string;
	alternativeBrandKey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	description:string;
} 

export interface ApCatalogDiagnosticTest { 
	key:string;
	testKey:string;
	catalogKey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApCdt { 
	key:string;
	typeLkey:string;
	cdtCode:string;
	description:string;
	classLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApCdtDentalAction { 
	key:string;
	dentalActionKey:string;
	cdtKey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApClinicalDocumentation { 
	key:string;
	patientKey:string;
	encounterKey:string;
	docTypeLkey:string;
	docCategoryLkey:string;
	docContent:string;
	userKey:string;
	userRoleLkey:string;
	facilityKey:string;
	docStatusLkey:string;
	docFormTypeKey:string;
	docFormKey:string;
	createdDatetime:Date;
	approvedDatetime:Date;
	approvedByUserKey:string;
	approvedByUserRoleLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApComplaintSymptoms { 
	key:string;
	patientKey:string;
	encounterKey:string;
	chiefComplaint:string;
	onsetDate:number;
	duration:number;
	unitLkey:string;
	painCharacteristics:string;
	painLocationLkey:string;
	radiation:string;
	aggravatingFactors:string;
	relievingFactors:string;
	associatedSymptoms:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	cancellationReason:string;
	statusLkey:string;
} 

export interface ApConsultationOrder { 
	key:string;
	patientKey:string;
	visitKey:string;
	consultantSpecialtyLkey:string;
	cityLkey:string;
	preferredConsultantKey:string;
	consultationMethodLkey:string;
	consultationTypeLkey:string;
	consultationContent:string;
	notes:string;
	statusLkey:string;
	viewResponse:string;
	resposeStatusLkey:string;
	submissionDate:number;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	cancellationReason:string;
} 

export interface ApCpt { 
	key:string;
	categoryLkey:string;
	cptCode:string;
	description:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApCustomeInstructions { 
	key:string;
	prescriptionMedicationsKey:string;
	dose:number;
	frequencyLkey:string;
	unitLkey:string;
	roaLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApDentalAction { 
	key:string;
	description:string;
	type:string;
	imageName:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	favorite:boolean;
} 

export interface ApDentalChart { 
	key:string;
	encounterKey:string;
	patientKey:string;
	chartDate:Date;
	type:string;
	chartSequence:number;
	status:string;
	treatmentPlan:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApDentalChartProgressNote { 
	key:string;
	chartKey:string;
	note:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApDentalChartTooth { 
	key:string;
	chartKey:string;
	toothNumber:string;
	missing:boolean;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	toothNumberNumeric:number;
} 

export interface ApDentalPlannedTreatment { 
	key:string;
	patientKey:string;
	encounterKey:string;
	type:string;
	visitNumber:number;
	cdtKey:string;
	toothKey:string;
	note:string;
	surfaceLkey:string;
	billingTypeLkey:string;
	fees:number;
	insurance:number;
	discount:number;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	statusLkey:string;
	source:string;
	sourceKey:string;
} 

export interface ApDepartment { 
	key:string;
	facilityKey:string;
	name:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	departmentTypeLkey:string;
	appointable:boolean;
	hasTriage:boolean;
	departmentCode:string;
	phoneNumber:string;
	email:string;
	encountertypelkey:string;
} 

export interface ApDiagnosticCoding { 
	key:string;
	diagnosticsKey:string;
	codeTypeLkey:string;
	internationalCodeKey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
} 

export interface ApDiagnosticOrderTests { 
	key:string;
	patientKey:string;
	visitKey:string;
	statusLkey:string;
	orderKey:string;
	testKey:string;
	receivedLabKey:string;
	reasonLkey:string;
	priorityLkey:string;
	notes:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	processingStatusLkey:string;
	submitDate:number;
	orderTypeLkey:string;
	acceptedAt:number;
	acceptedBy:string;
	rejectedAt:number;
	rejectedBy:string;
	rejectedReason:string;
	patientArrivedAt:number;
	patientArrivedNoteRad:string;
	readyAt:number;
	approvedAt:number;
	cancellationReason:string;
} 

export interface ApDiagnosticOrderTestsNotes { 
	key:string;
	orderKey:string;
	testKey:string;
	notes:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApDiagnosticOrderTestsRadReport { 
	key:string;
	patientKey:string;
	visitKey:string;
	statusLkey:string;
	orderKey:string;
	medicalTestKey:string;
	orderTestKey:string;
	reportValue:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	orderTypeLkey:string;
	approvedAt:number;
	approvedBy:string;
	rejectedAt:number;
	rejectedBy:string;
	rejectedReason:string;
	reviewAt:number;
	reviewBy:string;
	severityLkey:string;
} 

export interface ApDiagnosticOrderTestsReportNotes { 
	key:string;
	orderKey:string;
	testKey:string;
	reportKey:string;
	notes:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApDiagnosticOrderTestsResult { 
	key:string;
	patientKey:string;
	visitKey:string;
	statusLkey:string;
	orderKey:string;
	medicalTestKey:string;
	orderTestKey:string;
	normalRangeKey:string;
	resultType:string;
	resultLkey:string;
	resultValueNumber:number;
	marker:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	processingStatusLkey:string;
	orderTypeLkey:string;
	approvedAt:number;
	approvedBy:string;
	rejectedAt:number;
	rejectedBy:string;
	rejectedReason:string;
	reviewAt:number;
	reviewBy:string;
	resultText:string;
	testProfileKey:string;
	isProfile:boolean;
	normalRangeValue:string;
} 

export interface ApDiagnosticOrderTestsResultNotes { 
	key:string;
	orderKey:string;
	testKey:string;
	resultKey:string;
	notes:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApDiagnosticOrderTestsSamples { 
	key:string;
	orderKey:string;
	testKey:string;
	notes:string;
	unitLkey:string;
	quantity:number;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	sampleCollectedAt:number;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApDiagnosticOrders { 
	key:string;
	patientKey:string;
	visitKey:string;
	statusLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	orderId:string;
	saveDraft:boolean;
	submittedBy:string;
	submittedAt:number;
	isUrgent:boolean;
	labStatusLkey:string;
	radStatusLkey:string;
} 

export interface ApDiagnosticTest { 
	key:string;
	testTypeLkey:string;
	testName:string;
	internalCode:string;
	internationalCodeOne:string;
	internationalCodeTwo:string;
	internationalCodeThree:string;
	ageSpecific:boolean;
	genderSpecific:boolean;
	genderLkey:string;
	specialPopulation:boolean;
	price:number;
	currencyLkey:string;
	specialNotes:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	appointable:boolean;
} 

export interface ApDiagnosticTestAgeType { 
	key:string;
	testKey:string;
	ageFrom:number;
	ageTo:number;
	ageTypeLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApDiagnosticTestCatalogHeader { 
	key:string;
	description:string;
	typeLkey:string;
	departmentKey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	testKey:string;
	catalogKey:string;
} 

export interface ApDiagnosticTestEyeExam { 
	key:string;
	testKey:string;
	eyeExamCategoryLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApDiagnosticTestGenetics { 
	key:string;
	testKey:string;
	internationalCodingTypeLkey:string;
	childCodeLkey:string;
	pathologyCategoryLkey:string;
	specimenTypeLkey:string;
	methodologyLkey:string;
	turnaroundTime:string;
	timeUnitLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApDiagnosticTestLaboratory { 
	key:string;
	testKey:string;
	internationalCodingTypeLkey:string;
	childCodeLkey:string;
	labCatalogKey:string;
	propertyLkey:string;
	systemLkey:string;
	scaleLkey:string;
	reagentsLkey:string;
	methodLkey:string;
	testDurationTime:number;
	timeUnitLkey:string;
	resultType:string;
	resultUnitLkey:string;
	isProfile:boolean;
	sampleContainerLkey:string;
	sampleVolume:number;
	sampleVolumeUnitLkey:string;
	tubeColorLkey:string;
	testDescription:string;
	sampleHandling:string;
	turnaroundTime:number;
	turnaroundTimeUnitLkey:string;
	preparationRequirements:string;
	medicalIndications:string;
	associatedRisks:string;
	testInstructions:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	categoryLkey:string;
	tubeTypeLkey:string;
} 

export interface ApDiagnosticTestNormalRange { 
	key:string;
	testKey:string;
	genderLkey:string;
	ageFrom:number;
	ageFromUnitLkey:string;
	ageTo:number;
	ageToUnitLkey:string;
	conditionLkey:string;
	resultTypeLkey:string;
	resultText:string;
	resultLovKey:string;
	normalRangeTypeLkey:string;
	rangeFrom:number;
	rangeTo:number;
	criticalValue:boolean;
	criticalValueLessThan:number;
	criticalValueMoreThan:number;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	profileTestKey:string;
	isProfile:boolean;
} 

export interface ApDiagnosticTestNormalRangeLov { 
	key:string;
	testKey:string;
	normalRangeKey:string;
	lovLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApDiagnosticTestPathology { 
	key:string;
	testKey:string;
	internationalCodingTypeLkey:string;
	childCodeLkey:string;
	pathologyCategoryLkey:string;
	specimenTypeLkey:string;
	analysisProcedureLkey:string;
	turnaroundTime:string;
	timeUnitLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	testDescription:string;
	sampleHandling:string;
	medicalLndications:string;
	criticalValues:string;
	preparationRequirements:string;
	associatedRisks:string;
	pathCatalogKey:string;
} 

export interface ApDiagnosticTestProfile { 
	key:string;
	diagnosticTestKey:string;
	testName:string;
	resultUnitLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApDiagnosticTestRadiology { 
	key:string;
	testKey:string;
	internationalCodingTypeLkey:string;
	childCodeLkey:string;
	radCategoryLkey:string;
	imageDuration:string;
	timeUnitLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	testDescription:string;
	medicalIndications:string;
	turnaroundTimeUnitLkey:string;
	turnaroundTime:number;
	associatedRisks:string;
	radCatalogKey:string;
	propertyLkey:string;
	systemLkey:string;
	scaleLkey:string;
	reagentsLkey:string;
	methodLkey:string;
	timingLkey:string;
	resultType:string;
	resultUnitLkey:string;
	labCatalogLkey:string;
} 

export interface ApDiagnosticTestSpecialPopulation { 
	key:string;
	testKey:string;
	specialPopulationLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApDoctorRound { 
	key:string;
	patientKey:string;
	encounterKey:string;
	roundStartTime:number;
	practitionerKey:string;
	shiftLkey:string;
	initialNote:string;
	progressNote:string;
	specialEventNote:string;
	primaryDiagnosis:string;
	major:boolean;
	suspected:boolean;
	clinicalImpression:string;
	secondaryDiagnoses:string;
	patientStatusLkey:string;
	complicationsNoted:string;
	summaryStatement:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	statusLkey:string;
} 

export interface ApDoctorRoundStaff { 
	key:string;
	doctorRoundKey:string;
	userKey:string;
	responsibility:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	encounterKey:string;
	isPresent:boolean;
	patientKey:string;
} 

export interface ApDrugOrder { 
	key:string;
	patientKey:string;
	visitKey:string;
	statusLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	drugorderId:string;
	saveDraft:boolean;
	submittedBy:string;
	submittedAt:number;
} 

export interface ApDrugOrderMedications { 
	key:string;
	patientKey:string;
	visitKey:string;
	drugOrderKey:string;
	genericMedicationsKey:string;
	drugOrderTypeLkey:string;
	doseUnitLkey:string;
	roaLkey:string;
	frequency:number;
	priorityLkey:string;
	pharmacyDepartmentKey:string;
	dose:number;
	notes:string;
	prnIndication:string;
	specialInstructions:string;
	parametersToMonitor:string;
	startDateTime:number;
	maximumDose:number;
	genericSubstitute:boolean;
	chronicMedication:boolean;
	patientOwnMedication:boolean;
	administrationInstructions:string;
	duration:number;
	durationTypeLkey:string;
	statusLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	cancellationReason:string;
	indicationUseLkey:string;
	indicationIcd:string;
	indicationSnomed:string;
	indicationManually:string;
} 

export interface ApDuplicationCandidateSetup { 
	key:string;
	role:string;
	dateOfBirth:boolean;
	dob:boolean;
	lastName:boolean;
	documentNo:boolean;
	mobileNumber:boolean;
	gender:boolean;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
} 

export interface ApDvmRule { 
	key:string;
	screenMetadataKey:string;
	ruleDescription:string;
	fieldKey:string;
	fieldName:string;
	fieldDataType:string;
	isFieldLov:boolean;
	isFieldRef:boolean;
	ruleType:string;
	ruleValue:string;
	ruleValueTwo:string;
	isDependant:boolean;
	dependantRuleCheck:string;
	dependantRuleKey:string;
	validationType:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApElectrocardiogramEcg { 
	key:string;
	patientKey:string;
	encounterKey:string;
	indication:string;
	ecgLeadType:string;
	heartRate:number;
	prInterval:number;
	qrsDuration:number;
	qtInterval:number;
	stSegmentChangesLkey:string;
	waveAbnormalitiesLkey:string;
	rhythmAnalysis:string;
	ecgInterpretation:string;
	cancellationReason:string;
	statusLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
} 

export interface ApEncounter { 
	key:string;
	patientKey:string;
	patientFullName:string;
	patientAge:string;
	encounterStatusLkey:string;
	encounterClassLkey:string;
	encounterPriorityLkey:string;
	encounterTypeLkey:string;
	serviceTypeLkey:string;
	patientStatusLkey:string;
	episodeCareKey:string;
	basedOnLkey:string;
	basedOnKey:string;
	partOfEncounterKey:string;
	attendingPhysicianKey:string;
	responsiblePhysicianKey:string;
	facilityKey:string;
	appointmentKey:string;
	virtualService:boolean;
	plannedStartDate:Date;
	plannedEndDate:Date;
	actualStartDate:Date;
	actualEndDate:Date;
	actualLengthHrs:number;
	reasonLkey:string;
	primaryDiagnoseKey:string;
	dietPreferenceLkey:string;
	dietPreferenceText:string;
	valuableItemsText:string;
	specialArrangementLkey:string;
	specialArrangementText:string;
	specialCourtesyLkey:string;
	originLkey:string;
	admissionSource:string;
	readmission:boolean;
	dischargeDestination:string;
	dischargeDisposition:string;
	locationTypeLkey:string;
	locationKey:string;
	followUpEncounterKey:string;
	queueNumber:number;
	billingAccountKey:string;
	paymentTypeLkey:string;
	payerTypeLkey:string;
	payerKey:string;
	insurancePlan:string;
	payerMemberId:string;
	referralNumber:string;
	accessLevel:number;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	departmentKey:string;
	dischargeTypeLkey:string;
	actualLengthMinutes:number;
	chiefComplaint:string;
	hpiSummery:string;
	hpiKey:string;
	pastMedicalHistorySummery:string;
	pastMedicalHistoryKey:string;
	rosSummery:string;
	rosKey:string;
	assessmentSummery:string;
	assessmentKey:string;
	physicalExamSummery:string;
	physicalExamSummeryKey:string;
	progressNote:string;
	dischargeNote:string;
	dischargeSummery:string;
	visitId:string;
	encounterNotes:string;
	sourceName:string;
	physicalExamNote:string;
	planInstructionsLkey:string;
	visitTypeLkey:string;
	physicianKey:string;
	insuranceKey:string;
	resourceTypeLkey:string;
	resourceKey:string;
	planInstructionsNote:string;
	discharge:boolean;
} 

export interface ApEncounterAppliedService { 
	key:string;
	encounterKey:string;
	serviceKey:string;
	categoryLkey:string;
	source:string;
	sourceKey:string;
	extraDetails:string;
	price:number;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApEncounterVaccination { 
	key:string;
	patientKey:string;
	encounterKey:string;
	vaccineKey:string;
	vaccineBrandKey:string;
	vaccineDoseKey:string;
	vaccineLotNumber:string;
	dateAdministered:number;
	actualSide:string;
	administrationReactions:string;
	externalFacilityName:string;
	notes:string;
	reviewedBy:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	reviewedAt:number;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	cancellationReason:string;
	statusLkey:string;
} 

export interface ApFacility { 
	key:string;
	facilityId:string;
	facilityName:string;
	facilityNameOtherLang:string;
	tenantId:string;
	facilityRegistrationDate:Date;
	facilityEmailAddress:string;
	facilityBriefDesc:string;
	facilityAddressOtherLang:string;
	facilityLogoFile:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	facilityPhone1:string;
	facilityPhone2:string;
	facilityFax:string;
	facilityAddressId:string;
	facilityTypeLkey:string;
	facilityType:string;
	facilityAddress:string;
	roolKey:string;
	defaultCurrencyLkey:string;
} 

export interface ApFunctionalAssessment { 
	key:string;
	patientKey:string;
	encounterKey:string;
	mobilityAmbulation:boolean;
	transferringBedChair:boolean;
	stairClimbingAbility:boolean;
	feeding:boolean;
	toiletingAbility:boolean;
	bathingAbility:boolean;
	dressingAbility:boolean;
	groomingAbility:boolean;
	walkingDistance:boolean;
	balance:boolean;
	urinaryContinence:boolean;
	bowelContinence:boolean;
	useOfAssistiveDevices:boolean;
	needForAssistance:boolean;
	fallHistory:boolean;
	painDuringMovement:boolean;
	needForRehab:boolean;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	cancellationReason:string;
	statusLkey:string;
} 

export interface ApGeneralAssessment { 
	key:string;
	patientKey:string;
	encounterKey:string;
	positionStatusLkey:string;
	bodyMovementsLkey:string;
	levelOfConsciousnessLkey:string;
	facialExpressionLkey:string;
	speechLkey:string;
	moodBehaviorLkey:string;
	memoryRecent:boolean;
	memoryRemote:boolean;
	signsOfAgitation:boolean;
	signsOfDepression:boolean;
	signsOfSuicidalIdeation:boolean;
	signsOfSubstanceUse:boolean;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	cancellationReason:string;
	statusLkey:string;
	livingCondition:string;
	patientNeedHelp:boolean;
	supportingMembers:string;
	familyLocationLkey:string;
} 

export interface ApGenericMedication { 
	key:string;
	genericName:string;
	manufacturerLkey:string;
	usageInstructions:string;
	dosageFormLkey:string;
	expiresAfterOpening:boolean;
	expiresAfterOpeningValue:string;
	singlePatientUse:boolean;
	price:number;
	currencyLkey:string;
	priceListKey:string;
	cost:number;
	storageRequirements:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	code:string;
	roaLkey:string;
	marketingAuthorizationHolder:string;
} 

export interface ApGenericMedicationActiveIngredient { 
	key:string;
	genericMedicationKey:string;
	activeIngredientKey:string;
	strength:number;
	unitLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApGenericMedicationRoa { 
	key:string;
	genericMedicationKey:string;
	roaLkey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApGlobalSettings { 
	key:string;
	facilityKey:string;
	settingKey:string;
	settingValue:string;
	settingCategory:string;
	requireRestart:boolean;
	requirePasscode:boolean;
	fixedValue:boolean;
	forAdminUse:boolean;
	hiddenSetting:boolean;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApIcdCode { 
	key:string;
	icdVersion:string;
	icdCode:string;
	description:string;
	chapter:string;
	block:string;
	category:string;
	subcategory:string;
	fulldescription:string;
	includes:string;
	excludes1:string;
	excludes2:string;
	useadditionalcode:string;
	codefirst:string;
	codingguidelines:string;
	clinicaldescription:string;
	severity:string;
	synonyms:string;
	abbreviations:string;
	notes:string;
	requireSide:string;
	requireDetails:string;
	linkedWithAge:string;
	linkedWithGender:string;
	linkedWithDisease:string;
	moreSpecification:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApInpatientChiefComplain { 
	key:string;
	patientKey:string;
	encounterKey:string;
	chiefComplaint:string;
	provocation:string;
	palliation:string;
	qualityLkey:string;
	regionLkey:string;
	onsetDateTime:number;
	understanding:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	cancellationReason:string;
	statusLkey:string;
	severityLkey:string;
} 

export interface ApLabResultLog { 
	key:string;
	resultKey:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
	resultValue:string;
} 

export interface ApLanguages { 
	key:string;
	languageCode:string;
	languageName:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApLicense { 
	key:string;
	tenantId:string;
	licenseId:string;
	licenseKey:string;
	licenseType:string;
	startDate:Date;
	endDate:Date;
	activestatus:boolean;
	uuidHwKeys:string;
	facilityAddress:string;
	facilityLogoFile:string;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

export interface ApLicenseDetails { 
	key:string;
	tenantId:string;
	licenseId:string;
	facilityCount:number;
	bedCount:number;
	userCount:number;
	modules:string;
	facilityUsageCount:number;
	bedUsageCount:number;
	userUsageCount:number;
	lastUsageDate:Date;
	createdBy:string;
	updatedBy:string;
	deletedBy:string;
	createdAt:number;
	updatedAt:number;
	deletedAt:number;
	isValid:boolean;
} 

