export interface Screen {
  name: string;
  description?: string | null;
  icon: string;
  viewOrder: number;
  navPath: string;
}

export interface Module {
  name: string;
  description?: string | null;
  icon: string;
  viewOrder: number;
  screens: Screen[];
}

export const MODULES: Module[] =
 [
   { name: "System Setup",
    description: "",
    icon: "FaWrench",
    viewOrder: 0,
    screens: [
      { name: "Allergens", description: "Allergens setup", icon: "Fa500Px", viewOrder: 10, navPath: "allergens" },
      { name: "Potential Duplicate", description: "", icon: "FaInstalod", viewOrder: 15, navPath: "potintial-duplicate" },
      { name: "Brand Medications", description: "", icon: "FaBottleDroplet", viewOrder: 8, navPath: "brand-medications" },
      { name: "Lists of Value", description: "", icon: "FaList", viewOrder: 8, navPath: "lov-setup" },
      { name: "Modules & Screens", description: "", icon: "FaDesktop", viewOrder: 0, navPath: "modules-setup" },
      { name: "Data Validation Manager", description: "", icon: "FaDatabase", viewOrder: 1, navPath: "dvm" },
      { name: "Access Roles", description: "", icon: "FaKey", viewOrder: 2, navPath: "access-roles" },
      { name: "Facilities", description: "", icon: "FaBuilding", viewOrder: 3, navPath: "facilities" },
      { name: "Departments", description: "", icon: "FaHouseMedical", viewOrder: 4, navPath: "departments" },
      { name: "UOM Group", description: "", icon: "FaBox", viewOrder: 7, navPath: "uom-group" },
      { name: "Prescription Instructions", description: "", icon: "FaPrescriptionBottle", viewOrder: 15, navPath: "prescription-instructions" },
      { name: "Age Group", description: "Age Group Setup", icon: "FaBaby", viewOrder: 10, navPath: "age-group" },
      { name: "Practitioners", description: "", icon: "FaBriefcaseMedical", viewOrder: 5, navPath: "practitioners" },
      { name: "Active Ingredients", description: "", icon: "FaPills", viewOrder: 7, navPath: "active-ingredients" },
      { name: "Metadata (View)", description: "", icon: "FaTags", viewOrder: 0, navPath: "metadata" },
      { name: "Resources", description: "Resources setup", icon: "FaBilibili", viewOrder: 6, navPath: "resources" },
      { name: "Dental Actions", description: "", icon: "FaTeeth", viewOrder: 9, navPath: "dental-actions" },
      { name: "Users", description: "", icon: "FaUsers", viewOrder: 4, navPath: "users" },
      { name: "Catalog Setup", description: "Diagnostic tests catalog", icon: "FaBook", viewOrder: 14, navPath: "catalog" },
      { name: "Diagnostics Setup", description: "Define Diagnostic tests (Lab, Rad, Path)", icon: "FaMicroscope", viewOrder: 13, navPath: "diagnostics-test" },
      { name: "Vaccine Setup", description: "Vaccine", icon: "FaSyringe", viewOrder: 9, navPath: "vaccine-setup" },
      { name: "Procedure Setup", description: "", icon: "FaProductHunt", viewOrder: 10, navPath: "procedure-setup" },
      { name: "Room Bed Setup", description: "", icon: "FaBed", viewOrder: 16, navPath: "room" },
      { name: "Medication Matrix Setup", description: "", icon: "FaMendeley", viewOrder: 12, navPath: "med-matrix-setup" },
      { name: "Services Setup", description: "", icon: "FaSprayCanSparkles", viewOrder: 11, navPath: "services-setup" },
      { name: "Vaccine Schedule Setup", description: "define vaccine age time", icon: "FaSyringe", viewOrder: 8, navPath: "vaccines-schedule-setup" },
      { name: "Checklists", description: "Cheklist", icon: "FaAdn", viewOrder: 5, navPath: "checklists" },
      { name: "Operation Setup", description: "Major Operations", icon: "FaHeadSideMask", viewOrder: 10, navPath: "operation-setup" },
      { name: "Purchase Approval", description: "", icon: "FaBoxOpen", viewOrder: 10, navPath: "purchase-approvals-setup" },
      { name: "Questionnaire Setup", description: "", icon: "FaClipboardQuestion", viewOrder: 5, navPath: "questionnaire-setup" },
      { name: "Medication Schedule Setup", description: "", icon: "FaPlay", viewOrder: 9, navPath: "medication-schedule" },
      { name: "Duration Setup", description: "", icon: "FaClock", viewOrder: 9, navPath: "visit-duration-setup" },
      { name: "Clinical Protocols Setup", description: "where to define clinical protocols dynamically", icon: "FaStethoscope", viewOrder: 1, navPath: "" },
      { name: "Shift Setup", description: "", icon: "FaClock", viewOrder: 13, navPath: "shift-setup" },
      { name: "Supplier Setup", description: "Supplier Setup", icon: "FaRedRiver", viewOrder: 15, navPath: "supplier-setup" },
      { name: "Surgical Kits Setup", description: "", icon: "FaCheckToSlot", viewOrder: 10, navPath: "surgical-kits-setup" },
      { name: "User New", description: "", icon: "FaPersonArrowDownToLine", viewOrder: 0, navPath: "users-new" },
      { name: "Test Report Template Setup", description: "to link test radiology or pathology to specific template", icon: "FaList", viewOrder: 0, navPath: "report-result-template" },
      { name: "Products Setup", description: "setup for products that will be used in warehouse transactions", icon: "FaSitemap", viewOrder: 11, navPath: "inventory-product-setup" },
    ],
  },
  {name: "Coding Module",
    description: "Coding Module",
    icon: "FaCodepen",
    viewOrder: 1,
    screens: [
      { name: "Cpt", description: "", icon: "FaMicroscope", viewOrder: 0, navPath: "cpt-setup" },
      { name: "ICD-10", description: "list of ICD-10 codes for diagnosis", icon: "FaStethoscope", viewOrder: 0, navPath: "icd10-setup" },
      { name: "LOINC", description: "", icon: "FaDebian", viewOrder: 0, navPath: "loinc-setup" },
      { name: "CDT Codes", description: "International dental procedures codes", icon: "FaTooth", viewOrder: 1, navPath: "cdt-setup" },
      { name: "SNOMED-CT", description: "", icon: "FaDigitalOcean", viewOrder: 0, navPath: "" },
    ],
  },
  {name: "Front Desk Office",
    description: null,
    icon: "FaRegIdBadge",
    viewOrder: 2,
    screens: [
      { name: "Quick Appointment", description: "", icon: "FaClock", viewOrder: 2, navPath: "encounter-registration" },
      { name: "Patient Registration", description: "", icon: "FaFilePen", viewOrder: 1, navPath: "patient-profile" },
      { name: "Information Desk", description: "Search and view registered patients in specific facility", icon: "FaPersonRays", viewOrder: 0, navPath: "information-desk" },
      { name: "Files Merge", description: "", icon: "FaFolderTree", viewOrder: 3, navPath: "merge-patient-files" },
    ],
  },
  {name: "Scheduling",
    description: "",
    icon: "FaCalendarDay",
    viewOrder: 3,
    screens: [
      {
        name: "Scheduling Screen",
        description: "",
        icon: "FaCalendarDays",
        viewOrder: 0,
        navPath: "schedual-screen",
      },
    ],
  },
  {name: "Telemedicine",
    description: "",
    icon: "FaVideo",
    viewOrder: 4,
    screens: [{ name: "Tele Consultations Requests", description: "", icon: "FaVideo", viewOrder: 0, navPath: "tele-consultation-screen" }],
  },
  {name: "EMR Module",
    description: null,
    icon: "FaFileWaveform",
    viewOrder: 4,
    screens: [
      { name: "Electronic Medical Records", description: "", icon: "FaFileWaveform", viewOrder: 2, navPath: "patient-EMR" },
     
    ],
  },
   {name: "Clinics Management",
    description: null,
    icon: "FaStethoscope",
    viewOrder: 4,
    screens: [
     
      { name: "Patients Visits List", description: "", icon: "FaList", viewOrder: 1, navPath: "encounter-list" },
      { name: "Review Results", description: "", icon: "FaRegMessage", viewOrder: 3, navPath: "review-results" },
   
    ],
  },
   {name: "Inpatient Care",
    description: "",
    icon: "FaBed",
    viewOrder: 5,
    screens: [
      { name: "Inpatient List", description: "", icon: "FaBedPulse", viewOrder: 1, navPath: "inpatient-encounters-list" },
      { name: "Waiting List", description: "", icon: "FaClock", viewOrder: 0, navPath: "waiting-encounters-list" },
      
    ],
  },
  {name: "Day Case",
    description: "",
    icon: "FaPersonShelter",
    viewOrder: 6,
    screens: [{ name: "Day Case Patient List", description: "", icon: "FaPersonWalkingArrowRight", viewOrder: 0, navPath: "day-case-list" }
        
    ],
  },
   {name: "Emergency",
    description: "",
    icon: "FaExplosion",
    viewOrder: 6,
    screens: [
      { name: "Er Triage", description: "", icon: "FaCommentMedical", viewOrder: 1, navPath: "ER-triage" },
     
      { name: "Er Department", description: "", icon: "FaBriefcaseMedical", viewOrder: 3, navPath: "ER-department" },
      { name: "Er Dashboard", description: "", icon: "FaChartBar", viewOrder: 0, navPath: "ER-dashboard" },
     
    ],
  },
    {name: "Procedures",
    description: "",
    icon: "FaSquareParking",
    viewOrder: 7,
    screens: [{ name: "Procedure Requests List", description: "", icon: "FaClipboardUser", viewOrder: 0, navPath: "procedure-module" }],
  },
  {name: "Operation Theater",
    description: "",
    icon: "FaHeartPulse",
    viewOrder: 8,
    screens: [
      { name: "Operation Requests", description: "", icon: "FaOutdent", viewOrder: 1, navPath: "operation-module" },
      { name: "Recovery Room", description: "", icon: "FaClover", viewOrder: 2, navPath: "recovery-module" },
      { name: "Operation Room Materials", description: "", icon: "FaSyringe", viewOrder: 0, navPath: "operation-room-materials" },
    ],
  },
  {name: "Laboratory",
    description: "",
    icon: "FaFlask",
    viewOrder: 9,
    screens: [{ name: "Clinical Laboratory", description: "", icon: "FaFlaskVial", viewOrder: 0, navPath: "lab-module" }],
  },
  {name: "Radiology",
    description: "",
    icon: "FaXRay",
    viewOrder: 10,
    screens: [{ name: "Imaging Radiology", description: "", icon: "FaSkull", viewOrder: 0, navPath: "rad-module" }],
  },
  {name: "Pharmacy",
    description: "",
    icon: "FaPrescriptionBottleMedical",
    viewOrder: 11,
    screens: [
      { name: "Internal Drug Orders", description: "", icon: "FaPills", viewOrder: 0, navPath: "pharmacy-internal-orders" },
      { name: "ePrescriptions", description: "", icon: "FaPrescription", viewOrder: 1, navPath: "pharmacy-ePrescriptions" },
      { name: "Controlled Medications", description: "", icon: "FaBiohazard", viewOrder: 2, navPath: "pharmacy-controlled-medications" },
    ],
  },
  {name: "Inventory Management",
    description: "",
    icon: "FaBoxesPacking",
    viewOrder: 12,
    screens: [
      {
        name: "Inventory Transfer",
        description: "",
        icon: "FaTrowelBricks",
        viewOrder: 1,
        navPath: "inventory-transfer",
      },
      {
        name: "Inventory Transactions",
        description: "",
        icon: "FaTentArrowLeftRight",
        viewOrder: 0,
        navPath: "inventory-transaction",
      },
      {
        name: "Inventory Transfer Approval",
        description: "",
        icon: "FaBatteryHalf",
        viewOrder: 2,
        navPath: "inventory-transfer-approval",
      },
      { name: "Department Stock",
         description: "",
          icon: "FaPills", 
          viewOrder: 2, 
          navPath: "department-stock" },
      {
        name: "Products Catalog",
        description: "",
        icon: "FaBoxOpen",
        viewOrder: 3,
        navPath: "product-catalog",
      },
      {
        name: "Warehouse Setup",
        description: "",
        icon: "FaBox",
        viewOrder: 11,
        navPath: "warehouse-setup",
      },
      {
        name: "Warehouse Items Setup",
        description: "",
        icon: "FaBoxArchive",
        viewOrder: 11,
        navPath: "warehouse-items-setup",
      },
      
    ],
  },
  {name: "Billing & Finance",
    description: "",
    icon: "FaMoneyBill1",
    viewOrder: 12,
    screens: [
      {
        name: "Ledger Account",
        description: "",
        icon: "FaMobileRetro",
        viewOrder: 1,
        navPath: "",
      },
      {
        name: "Price Lists",
        description: "",
        icon: "FaMoneyBill",
        viewOrder: 0,
        navPath: "progress-notes",
      },
    ],
  },
  {name: "Purchasing",
    description: "",
    icon: "FaMobileRetro",
    viewOrder: 13,
    screens: [
      { name: "Supplier Management", description: "", icon: "FaBriefcase", viewOrder: 3, navPath: "" },
      { name: "Quotation Management", description: "", icon: "FaPenClip", viewOrder: 4, navPath: "" },
      { name: "Payment Tracking", description: "", icon: "FaCoins", viewOrder: 7, navPath: "" },
      { name: "List of Requisition", description: "", icon: "FaMoneyBills", viewOrder: 5, navPath: "list-of-requisition" },
      { name: "Purchase Return", description: "", icon: "FaArrowLeft", viewOrder: 8, navPath: "" },
      { name: "Purchase Requisition", description: "", icon: "FaRegPaperPlane", viewOrder: 0, navPath: "purchasing-requisition" },
      { name: "Requisition Approval", description: "", icon: "FaRegThumbsUp", viewOrder: 1, navPath: "" },
      { name: "Purchase Orders", description: "", icon: "FaCubes", viewOrder: 2, navPath: "" },
      { name: "Goods Receipt Note", description: "", icon: "FaBoxTissue", viewOrder: 6, navPath: "reset-password" },
    ],
  },
 
 

 
  
  
];
