export interface Screen {
  name: string;
  code:string;
  description?: string | null;
  icon: string;
  viewOrder: number;
  navPath: string;
}

export interface Module {
  name: string;
  description?: string | null;
  icon: string;
  viewOrder: number;
  screens: Screen[];
}

export const MODULES: Module[] =
 [
   { name: "System Setup",
    description: "",
    icon: "FaWrench",
    viewOrder: 0,
    screens: [
      { name: "Allergens",code:"ALLERGENS" ,description: "Allergens setup", icon: "Fa500Px", viewOrder: 10, navPath: "allergens" },
      { name: "Potential Duplicate", code: "POTENTIAL_DUPLICATE", description: "", icon: "FaInstalod", viewOrder: 15, navPath: "potintial-duplicate" },
      { name: "Brand Medications", code: "BRAND_MEDICATIONS", description: "", icon: "FaBottleDroplet", viewOrder: 8, navPath: "brand-medications" },
      { name: "Lists Of Value", code: "LISTS_OF_VALUE", description: "", icon: "FaList", viewOrder: 8, navPath: "lov-setup" },
      { name: "Modules And Screens", code: "MODULES_AND_SCREENS", description: "", icon: "FaDesktop", viewOrder: 0, navPath: "modules-setup" },
      { name: "Data Validation Manager", code: "DATA_VALIDATION_MANAGER", description: "", icon: "FaDatabase", viewOrder: 1, navPath: "dvm" },
      { name: "Access Roles", code: "ACCESS_ROLES", description: "", icon: "FaKey", viewOrder: 2, navPath: "access-roles" },
      { name: "Facilities", code: "FACILITIES", description: "", icon: "FaBuilding", viewOrder: 3, navPath: "facilities" },
      { name: "Departments", code: "DEPARTMENTS", description: "", icon: "FaHouseMedical", viewOrder: 4, navPath: "departments" },
      { name: "Uom Group", code: "UOM_GROUP", description: "", icon: "FaBox", viewOrder: 7, navPath: "uom-group" },
      { name: "Prescription Instructions", code: "PRESCRIPTION_INSTRUCTIONS", description: "", icon: "FaPrescriptionBottle", viewOrder: 15, navPath: "prescription-instructions" },
      { name: "Age Group", code: "AGE_GROUP", description: "Age Group Setup", icon: "FaBaby", viewOrder: 10, navPath: "age-group" },
      { name: "Practitioners", code: "PRACTITIONERS", description: "", icon: "FaBriefcaseMedical", viewOrder: 5, navPath: "practitioners" },
      { name: "Active Ingredients", code: "ACTIVE_INGREDIENTS", description: "", icon: "FaPills", viewOrder: 7, navPath: "active-ingredients" },
      { name: "Metadata", code: "METADATA", description: "", icon: "FaTags", viewOrder: 0, navPath: "metadata" },
      { name: "Resources", code: "RESOURCES", description: "Resources setup", icon: "FaBilibili", viewOrder: 6, navPath: "resources" },
      { name: "Dental Actions", code: "DENTAL_ACTIONS", description: "", icon: "FaTeeth", viewOrder: 9, navPath: "dental-actions" },
      { name: "Users", code: "USERS", description: "", icon: "FaUsers", viewOrder: 4, navPath: "users" },
      { name: "Catalog Setup", code: "CATALOG_SETUP", description: "Diagnostic tests catalog", icon: "FaBook", viewOrder: 14, navPath: "catalog" },
      { name: "Diagnostics Setup", code: "DIAGNOSTICS_SETUP", description: "Define Diagnostic tests (Lab, Rad, Path)", icon: "FaMicroscope", viewOrder: 13, navPath: "diagnostics-test" },
      { name: "Vaccine Setup", code: "VACCINE_SETUP", description: "Vaccine", icon: "FaSyringe", viewOrder: 9, navPath: "vaccine-setup" },
      { name: "Procedure Setup", code: "PROCEDURE_SETUP", description: "", icon: "FaProductHunt", viewOrder: 10, navPath: "procedure-setup" },
      { name: "Room Bed Setup", code: "ROOM_BED_SETUP", description: "", icon: "FaBed", viewOrder: 16, navPath: "room" },
      { name: "Medication Matrix Setup", code: "MEDICATION_MATRIX_SETUP", description: "", icon: "FaMendeley", viewOrder: 12, navPath: "med-matrix-setup" },
      { name: "Services Setup", code: "SERVICES_SETUP", description: "", icon: "FaSprayCanSparkles", viewOrder: 11, navPath: "services-setup" },
      { name: "Vaccine Schedule Setup", code: "VACCINE_SCHEDULE_SETUP", description: "define vaccine age time", icon: "FaSyringe", viewOrder: 8, navPath: "vaccines-schedule-setup" },
      { name: "Checklists", code: "CHECKLISTS", description: "Cheklist", icon: "FaAdn", viewOrder: 5, navPath: "checklists" },
      { name: "Operation Setup", code: "OPERATION_SETUP", description: "Major Operations", icon: "FaHeadSideMask", viewOrder: 10, navPath: "operation-setup" },
      { name: "Purchase Approval", code: "PURCHASE_APPROVAL", description: "", icon: "FaBoxOpen", viewOrder: 10, navPath: "purchase-approvals-setup" },
      { name: "Questionnaire Setup", code: "QUESTIONNAIRE_SETUP", description: "", icon: "FaClipboardQuestion", viewOrder: 5, navPath: "questionnaire-setup" },
      { name: "Medication Schedule Setup", code: "MEDICATION_SCHEDULE_SETUP", description: "", icon: "FaPlay", viewOrder: 9, navPath: "medication-schedule" },
      { name: "Visit Duration", code: "VISIT_DURATION", description: "", icon: "FaClock", viewOrder: 9, navPath: "visit-duration-setup" },

      { name: "Clinical Protocols Setup", code: "CLINICAL_PROTOCOLS_SETUP", description: "where to define clinical protocols dynamically", icon: "FaStethoscope", viewOrder: 1, navPath: "" },
      { name: "Shift Setup", code: "SHIFT_SETUP", description: "", icon: "FaClock", viewOrder: 13, navPath: "shift-setup" },
      { name: "Supplier Setup", code: "SUPPLIER_SETUP", description: "Supplier Setup", icon: "FaRedRiver", viewOrder: 15, navPath: "supplier-setup" },
      { name: "Surgical Kits Setup", code: "SURGICAL_KITS_SETUP", description: "", icon: "FaCheckToSlot", viewOrder: 10, navPath: "surgical-kits-setup" },
      { name: "User New", code: "USER_NEW", description: "", icon: "FaPersonArrowDownToLine", viewOrder: 0, navPath: "users-new" },
      { name: "Test Report Template Setup", code: "TEST_REPORT_TEMPLATE_SETUP", description: "to link test radiology or pathology to specific template", icon: "FaList", viewOrder: 0, navPath: "report-result-template" },
      { name: "Products Setup", code: "PRODUCTS_SETUP", description: "setup for products that will be used in warehouse transactions", icon: "FaSitemap", viewOrder: 11, navPath: "inventory-product-setup" },

    ],
  },
  {name: "Coding Module",
    description: "Coding Module",
    icon: "FaCodepen",
    viewOrder: 1,
    screens: [
      { name: "Cpt",code:"CPT", description: "", icon: "FaMicroscope", viewOrder: 0, navPath: "cpt-setup" },
      { name: "Icd 10", code: "ICD_10", description: "list of ICD-10 codes for diagnosis", icon: "FaStethoscope", viewOrder: 0, navPath: "icd10-setup" },
      { name: "Loinc", code: "LOINC", description: "", icon: "FaDebian", viewOrder: 0, navPath: "loinc-setup" },
      { name: "Cdt Codes", code: "CDT_CODES", description: "International dental procedures codes", icon: "FaTooth", viewOrder: 1, navPath: "cdt-setup" },
      { name: "Snomed Ct", code: "SNOMED_CT", description: "", icon: "FaDigitalOcean", viewOrder: 0, navPath: "" },


    ],
  },
  {name: "Front Desk Office",
    description: null,
    icon: "FaRegIdBadge",
    viewOrder: 2,
    screens: [
      { name: "Quick Appointment",code:"QUICK_APPOINTMENT", description: "", icon: "FaClock", viewOrder: 2, navPath: "encounter-registration" },
      { name: "Patient Registration", code: "PATIENT_REGISTRATION", description: "", icon: "FaFilePen", viewOrder: 1, navPath: "patient-profile" },
      { name: "Information Desk", code: "INFORMATION_DESK", description: "Search and view registered patients in specific facility", icon: "FaPersonRays", viewOrder: 0, navPath: "information-desk" },
      { name: "Files Merge", code: "FILES_MERGE", description: "", icon: "FaFolderTree", viewOrder: 3, navPath: "merge-patient-files" },
    ],
  },
  {name: "Scheduling",
    description: "",
    icon: "FaCalendarDay",
    viewOrder: 3,
    screens: [
      {
        name: "Scheduling Screen",
        code:"SCHEDULING_SCREEN",
        description: "",
        icon: "FaCalendarDays",
        viewOrder: 0,
        navPath: "schedual-screen",
      },
    ],
  },
  {name: "Telemedicine",
    description: "",
    icon: "FaVideo",
    viewOrder: 4,
    screens: [{ name: "Tele Consultations Requests",
      code:"TELE_CONSULTATIONS_REQUESTS",
       description: "", 
       icon: "FaVideo", 
       viewOrder: 0, navPath: "tele-consultation-screen" }],
  },
  {name: "EMR Module",
    description: null,
    icon: "FaFileWaveform",
    viewOrder: 4,
    screens: [
      { name: "Electronic Medical Records",
        code:"ELECTRONIC_MEDICAL_RECORDS",
         description: "",
          icon: "FaFileWaveform", viewOrder: 2, navPath: "patient-EMR" },
     
    ],
  },
   {name: "Clinics Management",
    description: null,
    icon: "FaStethoscope",
    viewOrder: 4,
    screens: [
     
      { name: "Patients Visits List", 
        code:"PATIENTS_VISITS_LIST",
        description: "", icon: "FaList",
         viewOrder: 1, navPath: "encounter-list" },
      { name: "Review Results", code: "REVIEW_RESULTS", description: "", icon: "FaRegMessage", viewOrder: 3, navPath: "review-results" },
   
    ],
  },
   {name: "Inpatient Care",
    description: "",
    icon: "FaBed",
    viewOrder: 5,
    screens: [
      { name: "Inpatient List",
        code:"INPATIENT_LIST",
         description: "",
          icon: "FaBedPulse", 
          viewOrder: 1, navPath: "inpatient-encounters-list" },
      { name: "Waiting List", code: "WAITING_LIST", description: "", icon: "FaClock", viewOrder: 0, navPath: "waiting-encounters-list" },
      
    ],
  },
  {name: "Day Case",
    description: "",
    icon: "FaPersonShelter",
    viewOrder: 6,
    screens: [{ name: "Day Case Patient List",
      code:"DAY_CASE_PATIENT_LIST",
       description: "", 
       icon: "FaPersonWalkingArrowRight", viewOrder: 0, navPath: "day-case-list" }
        
    ],
  },
   {name: "Emergency",
    description: "",
    icon: "FaExplosion",
    viewOrder: 6,
    screens: [
      { name: "Er Triage",
        code:"ER_TRIAGE",
         description: "", icon: "FaCommentMedical", viewOrder: 1, navPath: "ER-triage" },
     
      { name: "Er Department", code: "ER_DEPARTMENT", description: "", icon: "FaBriefcaseMedical", viewOrder: 3, navPath: "ER-department" },
      { name: "Er Dashboard", code: "ER_DASHBOARD", description: "", icon: "FaChartBar", viewOrder: 0, navPath: "ER-dashboard" },
     
    ],
  },
    {name: "Procedures",
    description: "",
    icon: "FaSquareParking",
    viewOrder: 7,
    screens: [{ name: "Procedure Requests List",
      code:"PROCEDURE_REQUESTS_LIST",
       description: "",
        icon: "FaClipboardUser", viewOrder: 0, navPath: "procedure-module" }],
  },
  {name: "Operation Theater",
    description: "",
    icon: "FaHeartPulse",
    viewOrder: 8,
    screens: [
      { name: "Operation Requests", 
        code:"OPERATION_REQUESTS",
        description: "",
         icon: "FaOutdent", viewOrder: 1, navPath: "operation-module" },
      { name: "Recovery Room", code: "RECOVERY_ROOM", description: "", icon: "FaClover", viewOrder: 2, navPath: "recovery-module" },
      { name: "Operation Room Materials", code: "OPERATION_ROOM_MATERIALS", description: "", icon: "FaSyringe", viewOrder: 0, navPath: "operation-room-materials" },
    ],
  },
  {name: "Laboratory",
    description: "",
    icon: "FaFlask",
    viewOrder: 9,
    screens: [{ name: "Clinical Laboratory",
      code:"Clinical_Laboratory",
       description: "", icon: "FaFlaskVial",
        viewOrder: 0, navPath: "lab-module" }],
  },
  {name: "Radiology",
    description: "",
    icon: "FaXRay",
    viewOrder: 10,
    screens: [{ name: "Imaging Radiology",
      code:"Imaging_Radiology",
       description: "", 
       icon: "FaSkull", viewOrder: 0, navPath: "rad-module" }],
  },
  {name: "Pharmacy",
    description: "",
    icon: "FaPrescriptionBottleMedical",
    viewOrder: 11,
    screens: [
      { name: "Internal Drug Orders",
        code:"Internal_Drug_Orders",
         description: "", icon: "FaPills", viewOrder: 0, navPath: "pharmacy-internal-orders" },
      { name: "ePrescriptions", code: "EPRESCRIPTIONS", description: "", icon: "FaPrescription", viewOrder: 1, navPath: "pharmacy-ePrescriptions" },
      { name: "Controlled Medications", code: "CONTROLLED_MEDICATIONS", description: "", icon: "FaBiohazard", viewOrder: 2, navPath: "pharmacy-controlled-medications" },
    ],
  },
  {name: "Inventory Management",
    description: "",
    icon: "FaBoxesPacking",
    viewOrder: 12,
    screens: [
      {
        name: "Inventory Transfer",
        code:"INVENTORY_TRANSFER",
        description: "",
        icon: "FaTrowelBricks",
        viewOrder: 1,
        navPath: "inventory-transfer",
      },
      {
        name: "Inventory Transactions", code: "INVENTORY_TRANSACTIONS",
        description: "",
        icon: "FaTentArrowLeftRight",
        viewOrder: 0,
        navPath: "inventory-transaction",
      },
      {
        name: "Inventory Transfer Approval", code: "INVENTORY_TRANSFER_APPROVAL",
        description: "",
        icon: "FaBatteryHalf",
        viewOrder: 2,
        navPath: "inventory-transfer-approval",
      },
      { name: "Department Stock", code: "DEPARTMENT_STOCK",
         description: "",
          icon: "FaPills", 
          viewOrder: 2, 
          navPath: "department-stock" },
      {
        name: "Products Catalog", code: "PRODUCTS_CATALOG",
        description: "",
        icon: "FaBoxOpen",
        viewOrder: 3,
        navPath: "product-catalog",
      },
      {
        name: "Warehouse Setup", code: "WAREHOUSE_SETUP",
        description: "",
        icon: "FaBox",
        viewOrder: 11,
        navPath: "warehouse-setup",
      },
      {
        name: "Warehouse Items Setup", code: "WAREHOUSE_ITEMS_SETUP",
        description: "",
        icon: "FaBoxArchive",
        viewOrder: 11,
        navPath: "warehouse-items-setup",
      },
      
    ],
  },
  {name: "Billing & Finance",
    description: "",
    icon: "FaMoneyBill1",
    viewOrder: 12,
    screens: [
      {
        name: "Ledger Account",
        code:"LEDGER_ACCOUNT",
        description: "",
        icon: "FaMobileRetro",
        viewOrder: 1,
        navPath: "",
      },
      {
        name: "Price Lists", code: "PRICE_LISTS",
        description: "",
        icon: "FaMoneyBill",
        viewOrder: 0,
        navPath: "progress-notes",
      },
    ],
  },
  {name: "Purchasing",
    description: "",
    icon: "FaMobileRetro",
    viewOrder: 13,
    screens: [
      { name: "Supplier Management",code:"Supplier_Management", description: "", icon: "FaBriefcase", viewOrder: 3, navPath: "" },
      { name: "Quotation Management", code: "QUOTATION_MANAGEMENT", description: "", icon: "FaPenClip", viewOrder: 4, navPath: "" },
      { name: "Payment Tracking", code: "PAYMENT_TRACKING", description: "", icon: "FaCoins", viewOrder: 7, navPath: "" },
      { name: "List of Requisition", code: "LIST_OF_REQUISITION", description: "", icon: "FaMoneyBills", viewOrder: 5, navPath: "list-of-requisition" },
      { name: "Purchase Return", code: "PURCHASE_RETURN", description: "", icon: "FaArrowLeft", viewOrder: 8, navPath: "" },
      { name: "Purchase Requisition", code: "PURCHASE_REQUISITION", description: "", icon: "FaRegPaperPlane", viewOrder: 0, navPath: "purchasing-requisition" },
      { name: "Requisition Approval", code: "REQUISITION_APPROVAL", description: "", icon: "FaRegThumbsUp", viewOrder: 1, navPath: "" },
      { name: "Purchase Orders", code: "PURCHASE_ORDERS", description: "", icon: "FaCubes", viewOrder: 2, navPath: "" },
      { name: "Goods Receipt Note", code: "GOODS_RECEIPT_NOTE", description: "", icon: "FaBoxTissue", viewOrder: 6, navPath: "reset-password" },
    ],
  },
 
 

 
  
  
];
